import test from 'node:test'
import assert from 'node:assert/strict'
import {admitNativeServiceRead} from '../lib/native-service-admission.mjs'
const owner='local_11111111-1111-4111-8111-111111111111',target='local_22222222-2222-4222-8222-222222222222',hash='a'.repeat(64)
function fixture(){const baseline={'.claude/settings.json':hash,'stop-rescue-policy.json':hash},hashes={'.claude-plugin/plugin.json':hash,'hooks/hooks.json':hash,'hooks/register.js':hash};return {config:{id:'b'.repeat(32),brokerSession:owner,brokerCwd:'/owned',build:hash,notBefore:500,deadline:30000,maxRequests:4},epoch:{pid:42,procStart:'synthetic',build:hash},ready:{schemaVersion:1,scope:'owned-native-service-ready',serviceId:'b'.repeat(32),brokerSession:owner,brokerCwd:'/owned',build:hash,registeredAt:new Date(600).toISOString(),deadline:30000,maxRequests:4,nativeCallsRequested:0,modelCallsRequested:0},broker:{sessionId:owner,live:{pid:42,procStart:'synthetic',entrypoint:'claude-desktop',status:'idle'},runtime:{build:hash,pinned:true,integrity:true}},versions:{app:'2.26454.0',cli:'2.1.289'},baseline,currentBaseline:{...baseline},hashes,installedHashes:{...hashes},controls:{stopped:false,armed:false,diagnostic:false},targetSession:target,now:1000,timeoutMs:20000}}
test('host preflight bounds one metadata request without modifying evidence or granting release',()=>{const x=fixture(),before=structuredClone(x),r=admitNativeServiceRead(x);assert.equal(r.admitted,true);assert.equal(r.expiresAt,21000);assert.equal(r.args.session_id,target);assert.equal(r.releaseAuthorized,false);assert.deepEqual(x,before);x.timeoutMs=60000;assert.equal(admitNativeServiceRead(x).expiresAt,30000)})
test('host refuses stale readiness, busy/changed epoch, controls, bytes and baseline before publication',()=>{
 for(const change of [x=>x.broker.live.status='busy',x=>x.broker.live.pid=43,x=>x.broker.live.procStart='changed',x=>x.broker.runtime.integrity=false,x=>x.controls.stopped=true,x=>x.controls.armed=true,x=>x.controls.diagnostic=true,x=>x.currentBaseline['.claude/settings.json']='changed',x=>x.installedHashes['hooks/register.js']='changed',x=>x.versions.cli='other',x=>x.targetSession=owner,x=>x.now=30001,x=>x.timeoutMs=60001]){const x=fixture();change(x);const r=admitNativeServiceRead(x);assert.equal(r.admitted,false);assert.equal(r.retrySafe,true)}
 const x=fixture();x.now=29500;assert.equal(admitNativeServiceRead(x).reason,'service_window_short')
})
