import test from 'node:test'
import assert from 'node:assert/strict'
import {screenNativePeerAdmission} from '../lib/native-peer-evidence.mjs'
const id='11111111-1111-4111-8111-111111111111',rid='rpeer'+id.replaceAll('-',''),start=1000,end=1100
const fixture=()=>({config:{id,targetSession:'local_target',brokerSession:'local_broker',deadline:2000},epoch:{build:'a'.repeat(64),pid:42,procStart:'synthetic'},pointer:{build:'a'.repeat(64),pid:42,procStart:'synthetic',sessionId:'local_broker',generation:6,bootstrapHash:'b'.repeat(64),activatedAt:new Date(500).toISOString()},request:{id:rid,protocol:7,ops:[{op:'get_session',args:{session_id:'local_target'}}],createdAt:new Date(900).toISOString(),expiresAt:2000},entry:{phase:'completed',requestId:rid,index:0,build:'a'.repeat(64),generation:6,bootstrapHash:'b'.repeat(64),at:1050,nativeBinding:{ancestorVerified:true,brokerPid:42,brokerProcStart:'synthetic',brokerSessionId:'local_broker'}},admission:{requestId:rid,index:0,pid:42,procStart:'synthetic',build:'a'.repeat(64),generation:6,toolUseId:'toolu_plugin_'+'a'.repeat(30),at:1060},control:{id:rid,dispatched:[0],state:'outcome_unknown'},report:{probeId:id,nativeCallReturned:true,resultWasError:false,failureCategory:null,startedAt:new Date(start).toISOString(),completedAt:new Date(end).toISOString()}})
test('one native read correlation does not settle standard lifecycle or authorize release',()=>{
 const result=screenNativePeerAdmission(fixture());assert.equal(result.singleReadAdmissionObserved,true);assert.equal(result.standardLifecycleSettled,false);assert.equal(result.nativeGateQualified,false)
 const legacy=fixture();delete legacy.entry.index;assert.equal(screenNativePeerAdmission(legacy).singleReadAdmissionObserved,true)
 for(const change of [x=>x.pointer.generation=7,x=>x.pointer.bootstrapHash='changed',x=>x.pointer.activatedAt=new Date(1200).toISOString(),x=>x.entry.phase='selected',x=>x.entry.index=1,x=>x.entry.nativeBinding.ancestorVerified=false,x=>x.admission.at=end+1,x=>x.admission.generation=7,x=>x.admission.toolUseId='foreign',x=>x.control.dispatched=[],x=>x.request.ops[0].args.extra=true,x=>x.request.expiresAt=1001,x=>x.report.resultWasError=true]){const x=fixture();change(x);assert.equal(screenNativePeerAdmission(x).singleReadAdmissionObserved,false)}
})
