import pathlib,json,subprocess,time
p=pathlib.Path(__file__).parent;b=['/Users/taylor/dotfiles/bin/ios-agent'];l=['--lease-file',str(p/'post-cancel-lease.json')]
def a(op,name,args={}):
 r=subprocess.run(b+['action',op,'--args',json.dumps(args)]+l+['--output',str(p/(name+'.json'))],capture_output=True);assert r.returncode==0,'native_rejection_inspect_private_no_replay';return json.load(open(p/(name+'.json')))['result']
def tap(d,n,name):
 r=n['rect'];return a('tap',name,{'snapshot':d['snapshot'],'target':n['node'],'x':r[0]+r[2]/2,'y':r[1]+r[3]/2})
d=a('tree','nested-nav');tap(d,next(n for n in d['nodes'] if n['visible'] and n['label'].startswith('Nutrition, tab,')),'nested-nav-tap')
subprocess.run(b+['verify','route','--expect','ClientMealLogs']+l+['--timeout','10','--output',str(p/'nested-nav-route.json')],check=True,capture_output=True)
time.sleep(.5);d=a('tree','nested-before');n=next(n for n in d['nodes'] if n['class']=='RCTEnhancedScrollView' and n['visible'] and n['rect'][2]<350 and n['rect'][3]<100);r=n['rect'];y=r[1]+r[3]/2;before=next(n['rect'] for n in d['nodes'] if n['visible'] and n['label']=='Fat: ');a('gesture','nested-horizontal',{'snapshot':d['snapshot'],'target':n['node'],'x':r[0]+r[2]-35,'y':y,'endX':r[0]+35,'endY':y,'durationMs':500});time.sleep(.5);d=a('tree','nested-after');after=next(n['rect'] for n in d['nodes'] if n['label']=='Fat: ');receipt={'horizontalChildMoved':abs(after[0]-before[0])>20,'verticalParentPositionPreserved':abs(after[1]-before[1])<1,'axisCompetitionScope':'actual horizontal child inside vertical meal ScrollView; no multi-touch claim'};assert all(receipt[k] for k in ['horizontalChildMoved','verticalParentPositionPreserved']);(p/'nested-summary.json').write_text(json.dumps(receipt,indent=2));print(json.dumps(receipt))
d=a('tree','atomic-history-fresh');n=next(n for n in d['nodes'] if n['class']=='RCTEnhancedScrollView' and n['visible'] and n['rect'][3]>600);a('gesture','atomic-history-scroll',{'snapshot':d['snapshot'],'target':n['node'],'x':190,'y':230,'endX':190,'endY':690,'durationMs':500});time.sleep(.5);d=a('tree','atomic-day-fresh');n=next(n for n in d['nodes'] if n['visible'] and n['class']=='RCTViewComponentView' and n['label'].startswith('Thu, Oct 1'));tap(d,n,'atomic-day-expand')
