import assert from'node:assert/strict';import fs from'node:fs';import{Backend}from'../mcp/backend.mjs';
const b=new Backend();let session;const receipt={at:new Date().toISOString(),scope:'Physical iPhone browser, guarded page-owned development control',gates:{}};
try{let pages=await b.webPages();const p=pages.pages.find(x=>x.browser===(process.argv[2]||'ios-safari')&&x.visible&&x.path==='/dev/ios-agent');assert(p);session=(await b.begin({surface:'web',page:p.id})).sessionId;const run=(action,args={})=>b.webAction({sessionId:session,action,args});
 const collision=await b.webEnroll({browser:'ios-chrome'});assert.equal(collision.actionSent,false);assert.equal(collision.ok,false);receipt.gates.browserLaunchBlockedDuringOwnership=true;
 await run('evaluate',{expression:`(()=>{const input=document.querySelector('#draft');input.readOnly=true;return true})()`});let s=await run('snapshot');let input=s.value.elements.find(e=>e.tag==='input');let r=await run('fill',{snapshot:s.value.snapshot,target:input.id,text:'must not write'});assert.equal(r.error,'editable_text_required');receipt.gates.readonlyFillRefused=true;
 await run('evaluate',{expression:`(()=>{document.querySelector('#draft').readOnly=false;const button=[...document.querySelectorAll('button')].find(b=>b.textContent==='Save test draft');const r=button.getBoundingClientRect();const blocker=document.createElement('div');blocker.id='runner-occlusion';blocker.style.cssText='position:fixed;z-index:2147483640;background:transparent;left:'+r.x+'px;top:'+r.y+'px;width:'+r.width+'px;height:'+r.height+'px';document.body.append(blocker);return true})()`});s=await run('snapshot');const button=s.value.elements.find(e=>e.label==='Save test draft'&&e.tag==='button');r=await run('click',{snapshot:s.value.snapshot,target:button.id});assert.equal(r.error,'target_not_interactable');receipt.gates.occludedClickRefused=true;
 await run('evaluate',{expression:`document.querySelector('#runner-occlusion').remove();true`});s=await run('snapshot');const offscreen=s.value.elements.find(e=>e.label==='Save after scrolling');r=await run('click',{snapshot:s.value.snapshot,target:offscreen.id});assert.equal(r.error,'target_not_interactable');receipt.gates.offscreenClickRefused=true;
 await new Promise(r=>setTimeout(r,800));const state=await run('state');receipt.wakeLock=state.value.wakeLock;receipt.sdkVersion=state.value.version;
 const end=await b.webEnd(session);assert(end.indicatorOff);session=null;receipt.gates.releaseGlowOff=true;
 fs.writeFileSync(new URL('../docs/mobile-web-edge-smoke-2026-10-09.json',import.meta.url),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
}finally{if(session){await b.webAction({sessionId:session,action:'evaluate',args:{expression:`document.querySelector('#runner-occlusion')?.remove();document.querySelector('#draft').readOnly=false;true`}}).catch(()=>{});await b.webEnd(session);}await b.close();}
