import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';import{Backend}from'../mcp/backend.mjs';
const require=createRequire('/Users/taylor/src/github/kickoff/next/package.json'),{webkit}=require('playwright');const browser=await webkit.launch({headless:true}),b=new Backend();let session;
const proof={at:new Date().toISOString(),scope:'Owned desktop WebKit real development page; lifecycle fault injection, not physical radio failure',gates:{}};
try{const enrollment=await b.webEnroll({});const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto(JSON.parse(fs.readFileSync(enrollment.launchFile)).url,{timeout:60000});await page.waitForFunction(()=>window.__iosWebAgent?.status().connected);const id=await page.evaluate(()=>window.__iosWebAgent.status().page);session=(await b.begin({surface:'web',page:id})).sessionId;
 await page.waitForFunction(()=>window.__iosWebAgent.status().indicator);await page.route('**/api/ios-web-agent',route=>route.abort());await page.waitForFunction(()=>!window.__iosWebAgent.status().indicator,{},{timeout:22000});proof.gates.pageWatchdogClearsOnTransportLoss=true;
 const released=await b.end(session);session=null;assert(released.released||released.alreadyInactive||released.ok);proof.gates.hostLeaseReleased=true;
 await page.unroute('**/api/ios-web-agent');await page.waitForFunction(()=>window.__iosWebAgent.status().connected);let p;for(let i=0;i<12;i++){p=(await b.webPages()).pages.find(p=>p.id===id&&p.visible);if(p)break;await new Promise(r=>setTimeout(r,1000));}assert(p);session=(await b.begin({surface:'web',page:id})).sessionId;
 const before=await page.evaluate(()=>({fetch:window.fetch,log:console.log})); // Functions cannot serialize; checks remain inside page.
 await page.evaluate(()=>{window.__runnerFetchReplacement=()=>Promise.resolve(new Response('replacement'));window.fetch=window.__runnerFetchReplacement;window.__runnerConsoleReplacement=()=>{};console.log=window.__runnerConsoleReplacement;window.__iosWebAgent.stop();});assert.equal(await page.evaluate(()=>window.fetch===window.__runnerFetchReplacement&&console.log===window.__runnerConsoleReplacement&&!document.querySelector('[data-ios-agent=indicator]')&&!window.__iosWebAgent),true);proof.gates.stopPreservesLaterWrappers=true;proof.gates.stopRemovesOwnedDOM=true;
 await b.end(session);session=null;fs.writeFileSync(new URL('../docs/mobile-web-lifecycle-2026-10-09.json',import.meta.url),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify(proof));
}finally{if(session)await b.end(session).catch(()=>{});await b.close();await browser.close();}
