from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,subprocess,shutil,re
service=Path('/Users/taylor/dotfiles/src/ios-agent');docs=service/'docs';report=Path('/Users/taylor/src/docs/html/iphone-link-status-update');private=Path(__file__).parent
now=datetime.now(timezone.utc).isoformat();v=json.loads((report/'report.json').read_text());native=v['qualificationPass']['nativeBuild']
gates={}
for group in ('unplugged','restore-on','release-cleanup'):
 for f in (private/group).glob('*.json'):
  r=json.loads(f.read_text())
  if 'gate' in r:gates[group+'/'+f.stem]=r['status'];assert r['status']=='passed'
for f in ('nutrition-delivery','home-delivery'):
 r=json.loads((private/'unplugged'/(f+'.json')).read_text());assert r['status']=='completed' and r['result']['delivered'] is True
state=json.loads((private/'restore-on/returned-state.json').read_text())['result'];assert state['wifiHandoff']['wifiInterface']['ipv4Present'] is True and state['wifiHandoff']['status']=='returned'
receipt={'version':1,'observedAt':now,'scope':'Latest snapshot/refresh/keep-awake installed DEV; Taylor confirmed USB unplugged; no Wi-Fi IPv4 association during wireless input','gates':gates,'nativeExecutableSHA256':native['nativeExecutableSHA256'],'embeddedJSSHA256':native['embeddedJSSHA256'],'usbUnpluggedConfirmed':True,'wifiIPv4DuringWireless':False,'wifiOnCallbackReturned':True,'wifiIPv4Restored':True,'settingsRadioSwitchDirectlyObserved':False,'nativeNutritionHomeDeliveryAndCommittedRoutes':True,'bundleSource':'tailnet-Metro','fallbackAttempted':False,'nativeHostIdle':True,'xctestUsed':False,'businessDataMutatedThisBatch':False,'privateEvidencePath':str(private),'limits':['App-owned foreground scope','Main-window capture cannot prove system occlusion','Fast Refresh may reset navigation/forms','Actual laptop sleep, VPN outage and shared backend cold restart not qualified']}
for dest in (docs,report/'evidence'):(dest/'recovery-wireless-final-2026-10-08.json').write_text(json.dumps(receipt,indent=2)+'\n')
cleanup={'version':1,'observedAt':now,'focusedChecks':10,'pythonSuite':86,'liveRetiredLeaseCleanup':True,'retiredCapabilityFileRemoved':True,'replacementOwnerPreservedByTests':True,'unconfirmedStateRetainsFile':True,'nativeHostIdle':True,'scope':'CLI cleanup; no automatic input replay or release of another owner'}
for dest in (docs,report/'evidence'):(dest/'release-cleanup-final-2026-10-08.json').write_text(json.dumps(cleanup,indent=2)+'\n')
v['observedAt']=v['updatedAt']=now;v['snapshot'].update(observedAt=now,scope='Latest snapshot/refresh/keep-awake installed DEV; USB unplugged qualification complete',nativeIdle=True,wifiHandoff='On callback returned and Wi-Fi IPv4 association restored after wireless testing.',cellularLatest='Passed newest installed native Nutrition→Home with USB unplugged and no Wi-Fi IPv4 association.',phoneNow='USB unplugged; DEV Home foreground; Wi-Fi association restored; no lease/glow/frontend or pending cleanup.')
q=v['qualificationPass'];q.update(updatedAt=now,pythonChecks=86,phoneReadiness=v['snapshot']['phoneNow'],unpluggedCellular='Latest snapshot/refresh/keep-awake binary passed; Wi-Fi restored; final native/host idle passed')
q['servicePublication']['commit']=subprocess.check_output(['git','-C','/Users/taylor/dotfiles','rev-parse','HEAD'],text=True).strip();q['servicePublication']['remoteMasterReadbackMatched']=True
items=v['items'];items[2]['gate']='Private wireless transport and newest installed-build unplugged input passed; readiness remains per-lease.'
items[10]['summary']='51 compiled UIKit gates plus representative real-phone navigation, focus/replace/Save, nested scroll, dedicated meal hold, readable UIKit menus and cleanup passed.'
items[10]['children'][0]['text']='51 compiled UIKit gates passed, including label precedence/redaction, bounded snapshot acknowledgment and prior idle-timer restoration. Owned simulator fixture cleanup passed.'
s=items[12];s.update(status='complete',summary='Bounded recovery qualification passed: latest-build wireless input, one-shot startup fallback, scoped worker outage and clean reacquisition. Fast Refresh route preservation failed and is explicitly excluded.',note='Complete means recovery evaluation and the stated bounded operating strategy are qualified. It does not mean state-preserving Fast Refresh or every network outage is supported.')
s['children']=[{'status':'complete','text':'Guarded warm backend reuse passed without stopping workers/resetting data. Controlled shared backend cold recovery is not qualified.'},{'status':'complete','text':'Presentation edit recorded component refresh, unchanged JS bundle generation and navigation reset to Home. Source restored; no business changes. Agents must gate ready/route after edits; state preservation failed.'},{'status':'deferred','text':'Actual laptop sleep/wake, tailnet VPN outage, shared backend cold restart and broader form-preservation tests require a separate controlled window; no success is claimed.'},{'status':'complete','text':'One 45-second pre-registration fallback physically verified: control retires, embedded app registers, no retry loop.'},{'status':'complete','text':'35-second owned-worker outage retired old control; fresh readiness recovered in 1.633 seconds with the same native boot. No input was sent or replayed during this outage.'},{'status':'complete','text':'Absolute deadlines and unknown-result receipts are implemented. Unit/IPC tests cover uncertain input; agents independently inspect state instead of replaying accepted actions.'},{'status':'complete','text':'Newest installed bounded-snapshot/keep-awake SDK passed USB-unplugged app, backend, remote Metro, React/native inspection and committed Nutrition→Home. Wi-Fi On association and idle restored.'},{'status':'complete','text':'Release now safely cleans an already-retired lease file. Live cleanup passed; replacement-owner preservation and unconfirmed-state failures passed focused tests. Full Python suite: 86.'}]
s['evidence']+=['recovery-wireless-final-2026-10-08.json','release-cleanup-final-2026-10-08.json']
s['gate']='Repeatable bounded recovery evidence, explicit failed/unqualified cases, fresh per-lease readiness and no leaked control after tested failures.'
s=items[14];s['summary']='Latest installed service and wireless smoke passed; runbook and runtime integration review complete. Coordinating shared tracked changes before audited Kickoff publication.'
s['children'][1]={'status':'complete','text':'Installer/source/restart checks passed; full service suite 86 Python, 22 JavaScript and 51 compiled UIKit gates. Latest real-phone wireless acceptance passed separately.'}
s['children'][2]={'status':'complete','text':'App-owned native + React/domain + Tailscale remains first. Mirroring is nearby recovery; bounded WDA is explicit system fallback. State-preserving Fast Refresh is excluded.'}
s['children'][3]={'status':'partial','text':'Selected app hooks and paired helper reviewed; broad merged Node/Web checks passed. Audited Kickoff push remains blocked by unrelated tracked edits; Runner (2) was asked to settle its scoped work.'}
s['children'][4]={'status':'complete','text':'Latest live smoke restored Home/Wi-Fi and verified no owned lease, glow, frontend or pending cleanup. Source probes restored. Operator runbook and current evidence synchronized.'}
s['note']='No guard bypass or unrelated commit. Runner (2) coordination is authorized by Taylor; await its safe checkpoint before audited publication.'
s['evidence']+=['recovery-wireless-final-2026-10-08.json','DELIVERY.md','release-cleanup-final-2026-10-08.json']
items[15]['children'].append({'status':'deferred','text':'State-preserving refresh/forms, physical hardware keyboard/IME/multi-touch, actual machine sleep and shared cold-backend recovery remain separately unqualified extensions.'})
(report/'report.json').write_text(json.dumps(v,indent=2)+'\n');(report/'evidence/qualification-progress-2026-10-08.json').write_text(json.dumps(q,indent=2)+'\n')
readme=service/'README.md';s=readme.read_text();paragraph='The latest snapshot/refresh/keep-awake SDK passed USB-unplugged native Nutrition→Home, native/React inspection, remote Metro and fresh backend readiness through private Tailscale without a Wi-Fi IPv4 association. Wi-Fi On and Home were restored; native/host cleanup passed. Both coach/client edit directions and exact restoration passed on the earlier dated runtime. See docs/recovery-wireless-final-2026-10-08.json for the newest build identity and docs/DELIVERY.md for the agent operating contract.'
s=s.replace(s.split('\n\n')[1],paragraph,1).replace('65 Python checks pass','86 Python checks pass').replace('suite passed 18 checks','suite passed 22 checks').replace('matrix passed 31 gates','matrix passed 51 gates').replace('workflow acceptance remains open','workflow acceptance passed on the recorded paired runtime').replace('42-gate compiled fixture','51-gate compiled fixture').replace('Physical recovery qualification is pending; ordinary Fast Refresh may still reset navigation.','Latest installed wireless input and scoped-worker recovery passed; ordinary Fast Refresh may still reset navigation.');readme.write_text(s)
current='''# Current installed acceptance — 8 October 2026\n\nThe latest snapshot/refresh/keep-awake SDK passed the exact USB-unplugged\nwireless input gate without Wi-Fi IPv4 association, including strict readiness,\nremote Metro, fresh backend probe, native/React inspection and committed\nNutrition→Home. Wi-Fi On callback and association were restored. Native and\nhost lease/glow/frontend cleanup passed. See recovery-wireless-final-2026-10-08.json\nfor exact fingerprints. Python 86, JavaScript 22, compiled UIKit 51 passed.\n\nA scoped 35-second worker outage recovered fresh readiness in 1.633 seconds.\nFast Refresh can reset navigation while bundle generation stays unchanged;\nforms/state preservation is not qualified. Actual laptop sleep, VPN outage and\nshared cold backend are unqualified; do not infer their success. Agent runbook:\nDELIVERY.md. Historical records below describe their own dated builds.\n\n'''
p=docs/'QUALIFICATION.md';p.write_text(current+p.read_text())
p=docs/'CAPABILITY-EDGES.md';s=p.read_text().replace('Current binary fingerprints are in\nphysical-resume-smoke.json','Newest binary fingerprints are in\nrecovery-wireless-final-2026-10-08.json').replace('These fixes\nrequire their own compiled/installed verification; do not claim delivery yet.','These fixes passed the later compiled and installed native-label gates.');p.write_text(current+s)
p=docs/'WORKFLOWS.md';s=p.read_text();s=s.replace('This qualifies the\nhelper, not successful paired browser/phone sign-in or the product round trip.','The helper gate is separate from the later completed paired product round trip recorded below.');p.write_text(s)
p=docs/'STRATEGIES.md';s=p.read_text().replace('physical timed hold tested, full recognizer matrix pending','dedicated meal hold, nested child scroll and UIKit menu labels passed; hardware/IME/multi-touch remain unqualified');s+='\n## Final installed ranking — 8 October\n\nChampion 1 passed latest-build USB-unplugged native and React/domain access,\nbackend/Metro, restored Wi-Fi and final idle. The bounded snapshot acknowledgment\naddresses the observed stale-before-delivery rejection while preserving live\nhit/geometry fencing. Scoped worker outage and one-shot startup fallback passed.\nIts main remaining app-development edge is navigation/form state across refresh;\nverify route after edits rather than pretending preserved state. Champions 2/3\nremain fallbacks for system UI and independent observations. No evidence ranks\nthe primary as universally more capable than XCTest outside its app scope.\n';p.write_text(s)
resume='''# Current Runner checkpoint — 8 October 2026\n\n14/16 bounded qualification stages complete. Latest SDK wireless input passed\nafter Taylor unplugged USB. Wi-Fi On/association restored; Home foreground and\nno lease/glow/frontend/pending cleanup. Native 51, Python 86, JavaScript 22.\nNo XCTest or Mirroring needed for this final smoke. Current receipts:\nrecovery-wireless-final-2026-10-08.json and release-cleanup-final-2026-10-08.json.\n\nRemaining stage 15: audited Kickoff publication blocked by shared tracked edits.\nTaylor authorized coordination with Runner (2), chat\n01a11e05-c0e6-7923-b763-ad83b052845c. Message sent asking it to settle only its\nscoped changes at a verified safe checkpoint. Preserve all other workloads;\nno direct push/guard bypass. Wait for its completion/current tracked status.\nStage 16 is dev-only-scope deferral. Report is\n/Users/taylor/src/docs/html/iphone-link-status-update/index.html.\n\nDo not repeat passing baselines. Refresh may reset navigation; ready/route gate\nafter edits. Actual machine sleep, VPN outage and cold shared backend remain\nunqualified. Dotfiles AGENTS: commit all dirty files/push master before ending.\n\n'''
p=docs/'RESUME.md';old=p.read_text();marker='## Historical checkpoints';old=old[old.find(marker):] if marker in old else '## Historical checkpoints\n\n'+old;p.write_text(resume+old)
for name in ('QUALIFICATION.md','CAPABILITY-EDGES.md','WORKFLOWS.md','STRATEGIES.md','RESUME.md'):
 shutil.copyfile(docs/name,report/'evidence'/name)
html=report/'index.html';s=html.read_text();s=re.sub(r'<p class="lede">.*?</p>','<p class="lede">14 of 16 bounded qualification stages are complete. The newest build passed native control and rich inspection over Tailscale with USB unplugged and no Wi-Fi association. Wi-Fi is restored and control is idle. Recovery limits are captured; the remaining closeout is audited Kickoff publication, coordinated with its other agent.</p>',s,count=1)
s=s.replace('Latest-build cellular result; state-preservation and download-interruption matrix','Navigation/form preservation, actual laptop sleep and VPN-outage qualification').replace('Full error matrix, native networking and WebSockets; raw payloads are not exported','Native networking and WebSockets; raw payloads are not exported').replace('Turn this inspection into dependable scenario assertions','Arbitrary deep-state operations and complete tree reconstruction').replace('Typed domain operations and synthetic workflow state assertions','Typed domain operations beyond the qualified paired workflow').replace('Fixed Wi-Fi Off/On shortcuts qualified through USB; Mirroring and WDA are separate recovery routes','Fixed Wi-Fi Off/On shortcuts and app return qualified wirelessly; Mirroring/WDA retained for system recovery')
s=s.replace('The fixed Wi-Fi handoff adapter was added and installed during qualification; both callback returns passed; its newest native-input wireless gate remains open after a pre-delivery freshness rejection.','The newest snapshot/keep-awake native-input wireless gate passed. Wi-Fi association and clean idle were restored. Complete means the stated bounded qualification; refresh state preservation and disruptive shared-machine recovery scenarios remain unqualified.')
s=s.replace('Cellular remains pending.','This historical build is superseded by the latest wireless receipt.');s=s.replace('<li>Device qualification:',f'<li>Latest native executable SHA-256: <code>{native["nativeExecutableSHA256"]}</code></li><li>Latest embedded JS SHA-256: <code>{native["embeddedJSSHA256"]}</code></li><li>Device qualification:')
html.write_text(s)
print(json.dumps({'latestWirelessPassed':True,'wifiRestored':True,'completedStages':14,'remaining':'Kickoff audited publication coordination; deferred extensions'}))
