import fs from 'node:fs/promises';
import path from 'node:path';
import { acquireLock } from './store/lock.js';
import { readJsonl, writeJsonl, readJson, writeJson } from './store/jsonl-store.js';
import { createValidators, validateStore } from './validation.js';
import { quarantine } from './store/quarantine.js';
import { CONFIG_DIR, DATA_DIR, dataPath } from './paths.js';
import { nowIso, sha256, stableId, stableStringify } from './util.js';
import { normalizeCompanyName, normalizeDomain, normalizeTitle, sourceToCandidate } from './normalize.js';
import { rankJob } from './rank.js';
import { enabledSources, fetchSource, loadCursors } from './sources/index.js';
import { findExactPosting, deterministicDecision } from './dedupe/exact.js';
import { retrieveCandidates } from './dedupe/candidates.js';
import { judgeWithCerebras } from './dedupe/cerebras.js';
import { mergeJob } from './dedupe/merge.js';

const files = { companies:'companies.jsonl', jobs:'jobs.jsonl', postings:'postings.jsonl', runs:'ingestion-runs.jsonl', decisions:'dedupe-decisions.jsonl', events:'status-events.jsonl' };
const emptyTotals = () => ({ companies_created:0, jobs_created:0, jobs_updated:0, postings_created:0, postings_updated:0, merged:0, ignored:0, quarantined:0, errors:0 });
const loadState = async (dataDir=DATA_DIR) => Object.fromEntries(await Promise.all(Object.entries(files).map(async([key,file])=>[key,await readJsonl(path.join(dataDir,file))])));

function resolveCompany(candidate, companies, now, aliases={}) {
  const domain=normalizeDomain(candidate.domain); const normalized=normalizeCompanyName(aliases[candidate.company] || candidate.company); let company=companies.find(c=>(domain&&c.domain===domain)||c.normalized_name===normalized||c.aliases.map(normalizeCompanyName).includes(normalized));
  if(company) return {company,created:false}; const id=stableId('co',domain||normalized); company={schema_version:1,id,name:candidate.company,normalized_name:normalized,domain,aliases:[],created_at:now,updated_at:now}; companies.push(company); return {company,created:true};
}
function makeJob(candidate, companyId, now, postingId, profile) {
  const id=stableId('job',`${companyId}:${normalizeTitle(candidate.title)}:${candidate.location.display}:${candidate.source_external_id||candidate.posting_id}`); const job={schema_version:1,id,company_id:companyId,title:candidate.title,normalized_title:normalizeTitle(candidate.title),description:candidate.description,description_hash:sha256(candidate.description),location:candidate.location,salary:candidate.salary,status:'new',status_reason:null,published_at:candidate.published_at,published_at_inferred:candidate.published_at_inferred,first_seen_at:now,last_seen_at:now,created_at:now,updated_at:now,posting_ids:[postingId],fit:null,field_provenance:{description:postingId,salary:postingId,published_at:postingId}}; job.fit=rankJob(job,profile,[candidate.source]); return job;
}
function makePosting(candidate, jobId, now) { return {schema_version:1,id:candidate.posting_id,job_id:jobId,source:candidate.source,source_external_id:candidate.source_external_id,source_url:candidate.source_url,canonical_url:candidate.canonical_url,apply_url:candidate.apply_url,source_company_name:candidate.company,source_title:candidate.title,source_location:candidate.source_location,source_salary_raw:typeof candidate.source_salary_raw==='string'?candidate.source_salary_raw:candidate.source_salary_raw?JSON.stringify(candidate.source_salary_raw):null,source_published_at:candidate.published_at,source_record_hash:candidate.source_record_hash,raw_artifact_path:candidate.raw_artifact_path,first_seen_at:now,last_seen_at:now,active:candidate.active}; }

async function applyCandidate(raw, state, context) {
  const {profile,validate,totals,now,dataDir}=context; const candidate=sourceToCandidate(raw,now); const co=resolveCompany(candidate,state.companies,now,profile.company_aliases); if(co.created) totals.companies_created+=1; candidate.company_id=co.company.id;
  const existingPosting=findExactPosting(candidate,state.postings); if(existingPosting){ existingPosting.last_seen_at=now; existingPosting.active=candidate.active; const job=state.jobs.find(j=>j.id===existingPosting.job_id); if(job) job.last_seen_at=now; totals.postings_updated+=1; totals.ignored+=1; return; }
  const sameUrlPosting=state.postings.find(p=>(candidate.canonical_url&&p.canonical_url===candidate.canonical_url)||(candidate.apply_url&&p.apply_url===candidate.apply_url));
  let selected=sameUrlPosting?state.jobs.find(j=>j.id===sameUrlPosting.job_id):null,method=selected?'exact':'none',decision=selected?'same_job':'new_job',confidence=1,rationale=selected?'A normalized canonical or apply URL identifies the same job.':'No plausible canonical job candidate.',features=selected?{matching_url:true}:{}; const matches=selected?[]:retrieveCandidates(candidate,state.jobs,profile.dedupe.candidate_limit);
  for(const match of matches){ const det=deterministicDecision(candidate,match); if(det.decision==='same_job'&&det.confidence>=profile.dedupe.auto_merge_threshold){selected=match.job;method='deterministic';decision='same_job';confidence=det.confidence;rationale=det.rationale;features=match.features;break;} if(det.decision==='uncertain'&&process.env.CEREBRAS_TOKEN&&context.aiCalls<profile.dedupe.max_ai_decisions_per_run){context.aiCalls+=1;try{const ai=await judgeWithCerebras(candidate,match.job,{threshold:profile.dedupe.ai_confidence_threshold});method='cerebras';decision=ai.decision;confidence=ai.confidence;rationale=ai.reason;features=match.features;if(ai.merge){selected=match.job;break;}}catch(error){method='cerebras';decision='uncertain';confidence=0;rationale=`Cerebras judgment unavailable: ${error.message}`;features=match.features;}} }
  if(!selected){ const post=makePosting(candidate,'pending',now); const job=makeJob(candidate,co.company.id,now,post.id,profile); if(decision==='uncertain')job.fit.flags.push('possible_duplicate'); post.job_id=job.id; const vr=validate('job',job),pr=validate('posting',post); if(!vr.valid||!pr.valid){await quarantine({source:candidate.source,record:raw,errors:[...vr.errors,...pr.errors],dataDir});totals.quarantined+=1;return;} state.jobs.push(job);state.postings.push(post);totals.jobs_created+=1;totals.postings_created+=1;
  } else { const post=makePosting(candidate,selected.id,now); const sourceKinds=[...state.postings.filter(p=>p.job_id===selected.id).map(p=>p.source),candidate.source]; const fit=rankJob({...selected,salary:candidate.salary.confidence==='explicit'?candidate.salary:selected.salary},profile,sourceKinds); const merged=mergeJob(selected,{...candidate,description_hash:sha256(candidate.description)},post.id,fit,now); Object.assign(selected,merged); state.postings.push(post);totals.jobs_updated+=1;totals.postings_created+=1;totals.merged+=1; }
  state.decisions.push({schema_version:1,id:stableId('decision',`${candidate.posting_id}:${selected?.id||'new'}:${now}`),created_at:now,posting_candidate:candidate.posting_id,candidate_job_id:selected?.id||null,method,decision,confidence,features,prompt_version:method==='cerebras'?'job-hunter-dedupe-v1':null,model:method==='cerebras'?'gpt-oss-120b':null,rationale,outcome:selected?`merged_into:${selected.id}`:'created_new_job'});
}

async function persistState(state,cursors,dataDir=DATA_DIR){ await fs.mkdir(dataDir,{recursive:true}); await writeJsonl(path.join(dataDir,files.companies),state.companies); await writeJsonl(path.join(dataDir,files.jobs),state.jobs); await writeJsonl(path.join(dataDir,files.postings),state.postings); await writeJsonl(path.join(dataDir,files.decisions),state.decisions); await writeJsonl(path.join(dataDir,files.events),state.events); await writeJsonl(path.join(dataDir,files.runs),state.runs); await writeJson(path.join(dataDir,'source-cursors.json'),cursors); }

async function persistRawArtifact(raw,dataDir,at){const date=at.slice(0,10);const name=sha256(stableStringify(raw)).slice(7,27)+'.json';const rel=path.join('raw',raw.source||'unknown',date,name);const safe=raw.source==='linkedin_email'?{source:raw.source,source_external_id:raw.source_external_id,source_url:raw.source_url,company:raw.company,title:raw.title,location:raw.location,published_at:raw.published_at,gmail_message_id:raw.gmail_message_id,gmail_content_hash:raw.gmail_content_hash}:raw;await writeJson(path.join(dataDir,rel),safe);return `data/${rel}`;}

export async function ingest({sources,dryRun=false,noDashboard=false,gmailBatch=10,maxPerSource=null,fixtureInputs=null,dataDir=DATA_DIR,lockPath}={}) {
  const release=await acquireLock(`ingest${dryRun?' --dry-run':''}`,lockPath); const started=nowIso(); const run={schema_version:1,id:stableId('run',`${started}:${process.pid}`),started_at:started,completed_at:null,status:'running',dry_run:dryRun,sources:{},totals:emptyTotals(),command_version:'1.0.0'}; let gmailSession=null;
  try {
    const existing=await validateStore(dataDir); if(!existing.valid) throw new Error(`Existing store is invalid; refusing unsafe mutation:\n${existing.errors.join('\n')}`);
    const state=await loadState(dataDir); state.runs.push(run); const profile=await readJson(path.join(CONFIG_DIR,'search-profile.json')); const {validate}=await createValidators(); const cursors=await readJson(path.join(dataDir,'source-cursors.json'),{}); const names=sources?.length?sources:await enabledSources(); const candidateContext={profile,validate,totals:run.totals,now:started,dataDir,aiCalls:0};
    for(const source of names){ const counts={fetched:0,processed:0,errors:[]}; run.sources[source]=counts; try { let result=fixtureInputs?.[source] ?? await fetchSource(source,{cursors,gmailBatch,dryRun}); if(result instanceof Error)throw result;if(result&& !Array.isArray(result)){gmailSession=result.session||gmailSession;counts.message_records=result.session?.records||[];counts.errors.push(...(result.errors||[]));if(result.errors?.length)run.totals.errors+=1;result=result.candidates||[];} counts.fetched=result.length;if(maxPerSource&&result.length>maxPerSource){counts.truncated=true;result=result.slice(0,maxPerSource);}for(const raw of result){try{const prepared=dryRun?raw:{...raw,raw_artifact_path:await persistRawArtifact(raw,dataDir,started)};await applyCandidate(prepared,state,candidateContext);counts.processed+=1;}catch(error){counts.errors.push(`candidate: ${error.message}`);run.totals.errors+=1;run.totals.quarantined+=1;if(!dryRun)await quarantine({source,record:raw,errors:[error.message],dataDir});}}if(!dryRun&&!counts.errors.length&&!counts.truncated)cursors[source]={high_water_at:started,last_successful_run:started,overlap_hours:profile.overlap_hours}; } catch(error){counts.errors.push(error.message);run.totals.errors+=1;} }
    run.status=run.totals.errors?'partial_failure':'success'; if(!dryRun){ await persistState(state,cursors,dataDir); if(gmailSession){await gmailSession.acknowledgeDurable();await gmailSession.close();gmailSession=null;} run.completed_at=nowIso(); await writeJsonl(path.join(dataDir,files.runs),state.runs); if(!noDashboard){const {buildDashboard}=await import('./dashboard/build.js');await buildDashboard();} } else {run.completed_at=nowIso();if(gmailSession){await gmailSession.close();gmailSession=null;}}
    return run;
  } catch(error){ if(gmailSession) await gmailSession.close().catch(()=>{}); throw error; } finally {await release();}
}
