import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync,mkdirSync,readFileSync,rmSync,realpathSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {fixturePackage,protectedWrite} from './fixture-package.mjs'
import {importSourcePages} from './fixture-import.mjs'
function setup(){const root=mkdtempSync(join(realpathSync(tmpdir()),'fixture-import-'));const packages=join(root,'packages'),sources=join(root,'sources');mkdirSync(packages,{mode:0o700});mkdirSync(sources,{mode:0o700});const package_id=JSON.parse(fixturePackage({action:'create',references:[]},packages)).package_id;const page='sp_'+ 'a'.repeat(24);protectedWrite(join(sources,page+'.json'),{rows:[{id:17,client_id:5,amount:42,date:'2026-01-01',note:'SYNTHETIC private fixture text'}],hasMore:false,cellsTruncated:false});const args={package_id,table:'events',route_field:'client_id',page_ids:[page],routes:[{source_value:5,bundle_id:'fictional',date_shift_days:30}],fields:{id:{source:'id',kind:'id',namespace:'event'},client_id:{source:'client_id',kind:'id',namespace:'client'},amount:{source:'amount',kind:'number'},date:{source:'date',kind:'datetime'},note:{source:'note',kind:'text',replacements:{[page]:{'17':'Fictional transformed note'}}}}};return {root,packages,sources,page,args}}
test('imports structural fields and explicit text idempotently without returning rows',()=>{const x=setup();try{const result=JSON.parse(importSourcePages(x.args,x.sources,x.packages));assert.equal(result.importedRows,1);assert.equal(result.released,false);assert.equal(result.privacyCertified,false);assert.ok(!JSON.stringify(result).includes('note'));assert.deepEqual(JSON.parse(importSourcePages(x.args,x.sources,x.packages)),result);fixturePackage({action:'seal_bundle',package_id:x.args.package_id,bundle_id:'fictional'},x.packages);const out=JSON.parse(readFileSync(join(x.packages,x.args.package_id,'customers/fictional.json')));assert.equal(out.tables.events[0].date,'2026-01-31');assert.match(out.tables.events[0].id,/^event_[a-f0-9]{24}$/);assert.equal(out.tables.events[0].note,'Fictional transformed note')}finally{rmSync(x.root,{recursive:true,force:true})}})
test('refuses untransformed free text before writing any chunks',()=>{const x=setup();try{delete x.args.fields.note.replacements;assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_text_replacement_required/);assert.throws(()=>readFileSync(join(x.packages,x.args.package_id,'chunks/fictional/events')),/ENOENT/)}finally{rmSync(x.root,{recursive:true,force:true})}})
test('refuses path traversal and unrouteable sources',()=>{const x=setup();try{x.args.page_ids=['../raw'];assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_invalid/);x.args.page_ids=[x.page];x.args.routes[0].source_value=999;assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_route_missing/)}finally{rmSync(x.root,{recursive:true,force:true})}})

test('rejects duplicate pages and undeclared field omissions',()=>{const x=setup();try{x.args.page_ids=[x.page,x.page];assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_invalid/);x.args.page_ids=[x.page];delete x.args.fields.note;assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_omission_declaration_required/);x.args.omissions={note:'out-of-scope'};assert.deepEqual(JSON.parse(importSourcePages(x.args,x.sources,x.packages)).omissions,{note:'out-of-scope'})}finally{rmSync(x.root,{recursive:true,force:true})}})

test('preserves DECIMAL strings exactly without numeric precision loss',()=>{const x=setup();try{const page='sp_'+'b'.repeat(24);protectedWrite(join(x.sources,page+'.json'),{rows:[{id:17,client_id:5,amount:'12345678901234567890.123456',date:'2026-01-01',note:'synthetic'}],cellsTruncated:false});x.args.page_ids=[page];x.args.fields.amount={kind:'decimal',source:'amount'};x.args.fields.note.replacements={[page]:{'17':'Fictional transformed note'}};assert.equal(JSON.parse(importSourcePages(x.args,x.sources,x.packages)).importedRows,1);fixturePackage({action:'seal_bundle',package_id:x.args.package_id,bundle_id:'fictional'},x.packages);const out=JSON.parse(readFileSync(join(x.packages,x.args.package_id,'customers/fictional.json')));assert.equal(out.tables.events[0].amount,'12345678901234567890.123456')}finally{rmSync(x.root,{recursive:true,force:true})}})

test('preserves MySQL dateStrings wall time and microseconds during date shift',()=>{const x=setup();try{const page='sp_'+'c'.repeat(24);protectedWrite(join(x.sources,page+'.json'),{rows:[{id:17,client_id:5,amount:42,date:'2026-01-01 14:23:45.123456',note:'synthetic'}],cellsTruncated:false});x.args.page_ids=[page];x.args.fields.note.replacements={[page]:{'17':'Fictional transformed note'}};importSourcePages(x.args,x.sources,x.packages);fixturePackage({action:'seal_bundle',package_id:x.args.package_id,bundle_id:'fictional'},x.packages);const out=JSON.parse(readFileSync(join(x.packages,x.args.package_id,'customers/fictional.json')));assert.equal(out.tables.events[0].date,'2026-01-31 14:23:45.123456')}finally{rmSync(x.root,{recursive:true,force:true})}})

test('accepts real package hyphenated fictional bundle IDs',()=>{const x=setup();try{x.args.routes[0].bundle_id='cg-001';assert.equal(JSON.parse(importSourcePages(x.args,x.sources,x.packages)).chunks,1);fixturePackage({action:'seal_bundle',package_id:x.args.package_id,bundle_id:'cg-001'},x.packages);assert.equal(JSON.parse(readFileSync(join(x.packages,x.args.package_id,'customers/cg-001.json'))).bundleId,'cg-001')}finally{rmSync(x.root,{recursive:true,force:true})}})

test('explicit ID map preserves existing catalog identity and fails closed if missing',()=>{const x=setup();try{x.args.fields.client_id.mapping={'5':'existing-client-001'};importSourcePages(x.args,x.sources,x.packages);fixturePackage({action:'seal_bundle',package_id:x.args.package_id,bundle_id:'fictional'},x.packages);const out=JSON.parse(readFileSync(join(x.packages,x.args.package_id,'customers/fictional.json')));assert.equal(out.tables.events[0].client_id,'existing-client-001');x.args.fields.client_id.mapping={};assert.throws(()=>importSourcePages(x.args,x.sources,x.packages),/fixture_import_id_mapping_missing/)}finally{rmSync(x.root,{recursive:true,force:true})}})
