#!/usr/bin/env python3
"""Render a private, self-contained evidence report from a supplied probe bundle."""
import argparse
import base64
import html
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--evidence', type=Path, required=True)
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()

def image(name):
    return 'data:image/png;base64,' + base64.b64encode((args.evidence / name).read_bytes()).decode()

def figure(name, caption):
    return f'<figure><img src="{image(name)}" alt="{html.escape(caption)}"><figcaption>{html.escape(caption)}</figcaption></figure>'

strategy = Path(__file__).with_name('STRATEGY.md').read_text()
page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Capture foundations: live qualification</title>
<style>
:root{color-scheme:light;--ink:#17202b;--paper:#f2f4f6;--line:#c9d3dd;--blue:#24727a;--warn:#805410}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 "Avenir Next",system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:40px 24px 80px}h1{font-size:clamp(30px,5vw,48px);line-height:1.13;max-width:24ch;letter-spacing:-.025em}h2{font-size:27px;margin:48px 0 14px}h3{font-size:19px}p,li{max-width:76ch}a{color:var(--blue)}.lede{font-size:22px;max-width:58ch}nav{display:flex;gap:20px;flex-wrap:wrap}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0}img{width:100%;height:auto;background:#fff;display:block}figcaption{font-size:15px;margin:9px 0 22px}table{border-collapse:collapse;width:100%;font-size:16px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:14px 12px 14px 0}th{color:var(--blue)}button,summary{font:inherit;cursor:pointer}button{padding:10px 16px;color:var(--ink);background:white;border:1px solid var(--line);border-radius:5px}button[aria-pressed=true]{color:white;background:var(--blue)}.switch{display:flex;gap:8px;margin:14px 0}.note{border-left:4px solid var(--warn);padding:10px 18px;background:white}details{margin:24px 0;padding:18px;background:white}summary{font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.65 system-ui,sans-serif}code{font-size:.88em;overflow-wrap:anywhere}:focus-visible{outline:3px solid var(--blue);outline-offset:4px}@media(max-width:650px){main{padding:26px 16px}.pair{grid-template-columns:1fr}table{font-size:14px}th,td{padding-right:8px}}
</style><main><nav><a href="#evidence">View evidence</a><a href="#strategy">Service strategy</a><a href="#limits">Remaining checks</a></nav>
<h1>Capture foundations, tested on your Mac</h1><p class="lede">The source needs three kinds of evidence: what appeared, what received input, and which agent intended the action.</p><p>October 8, 2026. Initial qualification kit and strategy, with live source captures. The installed recorder was not changed or restarted. No Claude usage, input lock or new permissions.</p>
<section id="evidence"><h2>Pointer hiding has several layers</h2><p>Both captures below requested pointer hiding. The left still contains computer use’s separate “Software Cursor” window. Excluding that helper app removed it from the display screenshot on the right, while preserving the desktop experience. Streaming exclusion remains a delivery gate.</p><div class="pair">'''
page += figure('software-cursor-rect.png', 'Capture-level hiding: helper pointer remains below the text field.')
page += figure('software-cursor-rect-excluding-pid.png', 'Helper app excluded: pointer is gone; app-painted arrow remains.')
page += '''</div><p>Native recorded footage also retained a blinking text caret. Chrome isolated video retained a pointer-like automation residual near the HTML-menu button; its cause is still open. Capture configuration cannot be treated as a universal clean-footage guarantee.</p><h2>Child surfaces change the menu result</h2><p>The same native menu disappeared when child inclusion was disabled and appeared when enabled. Its nested submenu was captured too. This is one app/OS combination, not a cross-app guarantee.</p><div class="switch"><button data-image="without" aria-pressed="true">Child inclusion disabled</button><button data-image="with" aria-pressed="false">Child inclusion enabled</button></div>'''
page += f'<figure><img id="menu-image" src="{image("edge-menu-included-window-false.png")}" alt="Native menu omitted with child inclusion disabled"><figcaption id="menu-caption">Menu omitted from the display-bound window capture.</figcaption></figure>'
page += '''<h2>Input delivery beats global focus</h2><p>The destination-aware retest retained <strong>46 key/modifier events</strong> addressed to the fixture. The fixture was foreground for <strong>none of them</strong>. Another 646 events contributed counts only. A focus-only rule would discard legitimate agent input; those outside-scope counts are not a contamination rate.</p><p>All retained events named the current computer-use helper as source, but its zero-valued tags did not identify a durable agent session. Action receipts and uncertainty are still necessary. AX actions can change windows without a pointer event.</p>
<h2>Time and redundancy have useful foundations</h2><table><tr><th>Probe</th><th>Observed result</th><th>What remains</th></tr><tr><td>Frame clock and geometry</td><td>1,178 complete frames. Converted display time and PTS agreed within 1 ns. Screen rect followed an 80-point move.</td><td>Actual action-to-pixel bound; resizing, sleep/wake and display changes.</td></tr><tr><td>Capture callback</td><td>Median lag 0.391 ms; maximum 10.953 ms in this probe.</td><td>Realistic high-motion/load qualification.</td></tr><tr><td>Matched source lanes</td><td>Two 35-second, 1400×964 recordings; zero dropped frames. Isolated footage survived the display crop’s occlusion/move.</td><td>CPU, memory, encoder, thermal and storage budget. About 2.62 MB here is a small static-fixture result.</td></tr><tr><td>Shared computer use</td><td>Native control/typing/selection/menu/cleanup checks and bridge MCP discovery passed. History inventory found 2,555 calls in 32 chats since September 17.</td><td>Historical success audit and a fresh delegated bridge run. Counts/discovery prove neither.</td></tr></table></section>
<section id="strategy"><h2>The proposed service contract</h2><table><tr><th>Owner</th><th>Responsibilities</th></tr><tr><td>Shared computer-use capabilities</td><td>App/provider/version facts; action receipts; delivery evidence; broad canaries plus stable per-app depth lanes; human production expectations.</td></tr><tr><td>Recorder</td><td>Normalized host timeline and geometry segments; explicit child/overlay capture options; source coverage and disturbances; measured recovery/insurance lanes.</td></tr><tr><td>Agent/director</td><td>Intent and rich contextual blocks; semantic relevance refinements with reasons; choice of cost/fidelity and recovery plan.</td></tr><tr><td>Later composition phase</td><td>Cursor/effect recipes, transient reintegration, brief visual/audio cues and final rendering. Deferred here.</td></tr></table><p>Consumers should receive synchronized sources, event/action journals, transforms, context blocks and QA. They should not implement clock calibration or coordinate reconstruction. Verification levels progress from metadata, to sparse source frames, to short previews, to full rendering later.</p><p>Production modes should say whether work is background-cooperative, display-reserved or awaiting an approved interval. Detect interruptions and save the shot; do not block the user prophylactically. P80 estimates need actual measurements. A second display does not isolate every OS shortcut or focus effect.</p></section>
<section id="limits"><h2>The next qualification gates</h2><ol><li>Shared receipts and versioned app facts; concurrent user input and agent shortcuts with explicit uncertainty.</li><li>Recorder timeline/geometry segments, child inclusion and helper exclusions; verify streaming behavior and marker alignment.</li><li>Visible Chrome native menus, Electron and other daily apps; recovery checks and realistic redundancy benchmarks.</li><li>Consumer bundle and inexpensive source previews. Visual composition remains next phase.</li></ol><p class="note">The disposable fixture crashed while closing a retained AppKit window. Its lifetime handling was repaired, and closing the occlusion and main windows was verified. One telemetry run spanning the relaunch was discarded. The recorder remained available.</p><p>Chrome native input could not reach its off-Space window even though browser-tab automation worked. Several capture modes also returned SCK -3811 errors. The clean baseline and HTML-menu recording succeeded; native-menu reliability is still unresolved.</p></section>
<details><summary>Read the full implementation strategy and acceptance gates</summary><pre>'''
page += html.escape(strategy)
page += '</pre></details><details><summary>Evidence and repeatable kit</summary><p>Private artifacts: <code>' + html.escape(str(args.evidence)) + '</code></p><p>Source kit: <code>/Users/taylor/src/github/dotfiles/src/record-screen/qualification/</code></p><p>Recorder session: ses_znmm2ude. Recordings: rec_9ysm6u63, rec_329z2bru, rec_pwxrgkwx, rec_cu7uaw6w. Owned fixture, tab, servers and taps were closed/stopped; no active recordings remained.</p></details></main><script>'
page += 'const images=' + __import__('json').dumps({'without': image('edge-menu-included-window-false.png'), 'with': image('edge-menu-included-window-true.png')}) + ';'
page += '''for(const b of document.querySelectorAll('[data-image]'))b.addEventListener('click',()=>{for(const other of document.querySelectorAll('[data-image]'))other.setAttribute('aria-pressed',String(other===b));const shown=b.dataset.image==='with';document.querySelector('#menu-image').src=images[b.dataset.image];document.querySelector('#menu-image').alt=shown?'Native menu present with child inclusion enabled':'Native menu omitted with child inclusion disabled';document.querySelector('#menu-caption').textContent=shown?'Native menu included in the same display-bound window capture.':'Menu omitted from the display-bound window capture.'});</script></html>'''
args.output.write_text(page)
print(f'Report saved: {args.output} ({args.output.stat().st_size} bytes)')
