#!/usr/bin/env python3
"""Render a private, self-contained evidence report from a supplied probe bundle."""
import argparse
import base64
import html
import mimetypes
import json
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--evidence', type=Path, required=True)
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()

def image(name):
    mime = mimetypes.guess_type(name)[0] or 'image/png'
    return 'data:' + mime + ';base64,' + base64.b64encode((args.evidence / name).read_bytes()).decode()

def figure(name, caption):
    return f'<figure><img src="{image(name)}" alt="{html.escape(caption)}"><figcaption>{html.escape(caption)}</figcaption></figure>'

strategy = Path(__file__).with_name('STRATEGY.md').read_text()
page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Capture foundations: live qualification</title>
<style>
:root{color-scheme:light;--ink:#17202b;--paper:#f2f4f6;--line:#c9d3dd;--blue:#24727a;--warn:#805410}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 "Avenir Next",system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:40px 24px 80px}h1{font-size:clamp(30px,5vw,48px);line-height:1.13;max-width:24ch;letter-spacing:-.025em}h2{font-size:27px;margin:48px 0 14px}h3{font-size:19px}p,li{max-width:76ch}a{color:var(--blue)}.lede{font-size:22px;max-width:58ch}nav{display:flex;gap:20px;flex-wrap:wrap}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0}img{width:100%;height:auto;background:#fff;display:block}figcaption{font-size:15px;margin:9px 0 22px}table{border-collapse:collapse;width:100%;font-size:16px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:14px 12px 14px 0}th{color:var(--blue)}button,summary{font:inherit;cursor:pointer}button{padding:10px 16px;color:var(--ink);background:white;border:1px solid var(--line);border-radius:5px}button[aria-pressed=true]{color:white;background:var(--blue)}.switch{display:flex;gap:8px;margin:14px 0}.note{border-left:4px solid var(--warn);padding:10px 18px;background:white}details{margin:24px 0;padding:18px;background:white}summary{font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.65 system-ui,sans-serif}code{font-size:.88em;overflow-wrap:anywhere}:focus-visible{outline:3px solid var(--blue);outline-offset:4px}@media(max-width:650px){main{padding:26px 16px}.pair{grid-template-columns:1fr}table{font-size:14px}th,td{padding-right:8px}}
</style><main><nav><a href="#evidence">View evidence</a><a href="#strategy">Service strategy</a><a href="#limits">Remaining checks</a></nav>
<h1>Capture foundations, tested on your Mac</h1><p class="lede">The source needs three kinds of evidence: what appeared, what received input, and which agent intended the action.</p><p>October 8, 2026. Five staged qualification passes with live source captures and isolated candidate engines. The installed recorder was not changed or restarted. No Claude usage, input lock or new permissions.</p>
<section id="evidence"><h2>Pointer hiding has several layers</h2><p>Both captures below requested pointer hiding. The left still contains computer use’s separate “Software Cursor” window. Excluding that helper app removed it from the display screenshot on the right, while preserving the desktop experience. Streaming exclusion remains a delivery gate.</p><div class="pair">'''
if (args.evidence / 'gates-v2').exists():
    gate_notes = '## Second pass: live evidence' + Path(__file__).with_name('GATES.md').read_text().split('## Second pass: live evidence', 1)[1]
    update = '<section id="second-pass"><h2>Next gates: verified source evidence</h2><p>Live-stream helper exclusion passed, and Chrome’s visible native context menu was captured with child inclusion enabled. A 12-marker series matched every transition: median 8.13 ms, range 3.18–63.52 ms from fixture action handling to captured pixels.</p><p>Across 22 source frames, the candidate geometry transform matched the authored marker within 0.884 pixels through a move and resize. A private source-packet prototype joins relative times, geometry, delivery reasons and an action-block receipt. Raw input positions remain withheld until their coordinate semantics are qualified.</p><div class="pair">'
    update += figure('gates-v2/rect-retry/frame-00000.png', 'Live display stream: software pointer remains despite pointer hiding.')
    update += figure('gates-v2/excluded-retry/frame-00000.png', 'Live stream with verified helper app excluded: software pointer removed.')
    update += '</div><details><summary>Inspect Chrome’s native menu in a live source frame</summary>'
    update += figure('gates-v2/chrome-native-stream/frame-00567.png', 'Visible Chrome menu captured. Provider banner and pointer-like decoration also entered the source; this is not universally clean footage.')
    update += '</details><p class="note">Three concurrent standalone probe starts stalled; sequential retries succeeded. The native menu was absent through the 4.03-second sparse preview and present at 5.04 seconds. These findings require startup bounds and pixel presence checks. Their causes remain open.</p><p>The installed recorder remained unchanged. Concurrent user attribution, cross-display/sleep synchronization, daily-app depth lanes and realistic redundancy budgets still need qualification. Effects and composition remain deferred.</p><details><summary>Read second-pass evidence and remaining gates</summary><pre>' + html.escape(gate_notes) + '</pre></details></section>'
    page = page.replace('<section id="evidence">', update + '<section id="evidence"><p><strong>Initial pass evidence follows.</strong> Second-pass results above supersede its open streaming and visible-Chrome checks.</p>')
if (args.evidence / 'gates-v3/qualification-summary.json').exists():
    third_notes = '## Third pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Third pass:', 1)[1].split('## Second pass: live evidence', 1)[0]
    third = '<section id="third-pass"><h2>Next gates: background contracts and recovery</h2><p>The candidate engine builds and passes 25 target parsing and source-identity checks. Child settings, excluded apps and resolved PIDs now distinguish recording taps and preview lanes. Capability negotiation rejects a legacy engine before it can silently ignore requested options.</p><p>The shared computer-use layer now has four local evidence tools plus a model-free CLI. Two prior app observations and one declared action block were saved and independently read back. Exact version keys, expiry, conflicts, private publication and session scoping are tested.</p><p>A separate qualification supervisor passed synthetic stall, interruption, concurrent admission and recovery tests. It preserves partial evidence and stops only its owned helpers.</p><p class="note">These are source and background checks. The installed recorder remains unchanged. Production SDK routing, engine startup deadlines, automatic receipts, concurrent-user attribution and cross-display/menu/load qualification remain open. No new UI actions or visual composition in this pass.</p><details><summary>Read third-pass scope, evidence and remaining gates</summary><pre>' + html.escape(third_notes) + '</pre></details></section>'
    page = page.replace('<section id="second-pass">', third + '<section id="second-pass">')
if (args.evidence / 'gates-v4/journal-clock-proof.json').exists():
    fourth_notes = '## Fourth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Fourth pass:', 1)[1].split('## Third pass:', 1)[0]
    fourth = '<section id="fourth-pass"><h2>Next gates: signed engine, recovery and source timing</h2><p>The signed isolated engine passed native child-menu inclusion and exclusion, filter-aware preview routing, unavailable-target isolation, scheduled cancellation and recovery after an owned process interruption. The partial MP4 decoded 292 frames; saved manifest counters were stale and now carry a checkpoint warning.</p><p>A bounded recorder-owned journal preserves source frames, geometry segments, encoded and held-frame references, exact host times and declared marks. Live tests caught two timing problems: a default 600-tick video track and a separately quantized movie offset. Setting both timescales corrected them.</p><p><strong>All 1,337 encoded samples matched journal timestamps exactly</strong> across the corrected H.264 and Retina HEVC takes. The HEVC marker matched all three geometry segments within 0.884 pixels through movement and resizing. Both journals closed with zero reported telemetry loss.</p><div class="pair">'
    fourth += figure('gates-v4/encoded-menu.png', 'Actual encoded source footage preserved the native edge menu; app-painted arrow remains.')
    fourth += figure('gates-v4/hevc-proof-geometry-2.png', 'Actual Retina HEVC frame after resizing. Journal transform predicted marker edges within 0.884 pixels.')
    fourth += '</div><p class="note">Production still runs the original engine. These are bounded candidate/fixture results, not a universal app, cross-display, physical-input latency or resource guarantee. Input attribution, native action receipts, daily-app depth, collision/load gates and safe delivery remain open. Visual composition remains deferred.</p><details><summary>Read fourth-pass evidence, corrections and limits</summary><pre>' + html.escape(fourth_notes) + '</pre></details></section>'
    page = page.replace('<section id="third-pass">', fourth + '<section id="third-pass">')
if (args.evidence / 'gates-v5/final-input-proof.json').exists():
    fifth_notes = '## Fifth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Fifth pass:', 1)[1].split('## Fourth pass:', 1)[0]
    fifth = '<section id="fifth-pass"><h2>Next gates: scoped input and contextual actions</h2><p><strong>All 36 native key/modifier events matched delivered-event evidence; none required fixture foreground.</strong> A separate owned app received 40 key events, with zero addressed keys retained in the source after the action block closed. Outside-scope activity contributed counts only.</p><p>Recorder-stamped action blocks preserve intent, contextual detail and delivery uncertainty. The AX marker below changed inside its declared interval while another owned app covered the target. No mouse event was fabricated for that accessibility action.</p><div class="pair">'
    fifth += figure('gates-v5/input-marker-before.png', 'Encoded source before the declared AX action: red marker.')
    fifth += figure('gates-v5/input-marker-after.png', 'Encoded source after the AX action: green marker; app-painted arrow remains.')
    fifth += '</div><p>Real candidate restart preserved an interrupted block with unknown end time. Wrong callers were rejected, and the supported callback wrapper stored a rich shared receipt without replaying an operation. The final signed candidate matched eight more delivered keys, rejected five malformed requests, and returned its passive listener to inactive. Both new takes closed with zero telemetry loss; all 3,244 muxed video timestamps matched the source journals exactly.</p><p class="note">Production remains the original signed engine. Raw pointer coordinates and event-clock mapping remain unqualified. Context enumeration averaged 11.66 ms and peaked at 41.50 ms on the listener loop; move it off that loop before production latency/load recommendations. Secure input, tap faults, other providers, daily-app depth, cross-display/sleep and motion/insurance budgets remain open.</p><details><summary>Inspect fifth-pass evidence, corrections and limits</summary><pre>' + html.escape(fifth_notes) + '</pre></details></section>'
    page = page.replace('<section id="fourth-pass">', fifth + '<section id="fourth-pass">')
if (args.evidence / 'gates-v6/qualification-summary.json').exists():
    page = page.replace('<nav>', '<nav><a href="#sixth-pass">Latest qualification</a>', 1)
    sixth_notes = '## Sixth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Sixth pass:', 1)[1].split('## Fifth pass:', 1)[0]
    sixth = '<section id="sixth-pass"><h2>Sixth pass: displays, protected input and desktop recovery</h2><p>The background context sampler passed 113 blocked-query and lifecycle checks. Live main-loop refresh cost averaged 2.20 ms before the desktop failure, compared with 11.66 ms when it also enumerated windows. These are component costs, not guaranteed input latency.</p><p>The owned fixture moved from built-in Retina to the external display with a negative desktop origin, then returned. Four encoded marker frames matched their own geometry transforms exactly; 8,315 muxed timestamps and 24 delivered key/modifier events matched their source records.</p><div class="pair">'
    sixth += figure('gates-v6/cross-display-pixels-geometry-8.png', 'Built-in Retina: marker edges match the 2× transform.')
    sixth += figure('gates-v6/cross-display-pixels-geometry-41.png', 'External display: 1× content on the fixed encoded canvas; negative desktop origin maps correctly.')
    sixth += '</div><p>Explicit protected input produced enabled/ended gaps, omitted all 24 delivered protected events, then recovered six normal events. The secure field alone did not enable global protection for the injected provider. A healthy listener cannot establish complete keyboard coverage.</p><p><strong>A real WindowServer exit interrupted the Chrome take.</strong> Its cause is unknown. Partial video decoded 1,197 frames across 42.02 seconds, while the complete journal contained 1,210 accepted encoder submissions. The failed proof is retained. New source descriptors distinguish journal closure from video finalization; recovery must measure actual decodable coverage.</p><p>The surviving test engine bounded an unfinished SDK discovery at three seconds and refused a retry in 0.448 ms while keeping status/action recovery available. A fresh signed isolated process recovered and completed a Chrome take with 1,732 exact muxed timestamps and zero journal loss.</p><div class="pair">'
    sixth += figure('gates-v6/chrome-html-source.jpg', 'Actual encoded Chrome source includes the HTML menu; a pointer-like residual remains.')
    sixth += figure('gates-v6/chrome-native-source.jpg', 'Actual encoded source includes the genuine native context menu with child capture enabled.')
    sixth += '</div><p class="note">Browser-provider typing changed DOM text without app-addressed OS keyboard evidence. Bounded action candidates addressed to Codex remain uncertain. Production is still the original signed engine. Electron depth, raw pointer coordinates, sleep, exclusion lifetimes, realistic resource budgets, derivative mapping and release remain open.</p><details><summary>Inspect sixth-pass evidence and limits</summary><pre>' + html.escape(sixth_notes) + '</pre></details></section>'
    page = page.replace('<section id="fifth-pass">', sixth + '<section id="fifth-pass">')
page += figure('software-cursor-rect.png', 'Capture-level hiding: helper pointer remains below the text field.')
page += figure('software-cursor-rect-excluding-pid.png', 'Helper app excluded: pointer is gone; app-painted arrow remains.')
page += '</div><details><summary>Inspect the surviving caret and browser automation pointer in actual video</summary><div class="pair">'
page += figure('native-video-caret.jpg', 'Native video: blue text caret and magenta app-painted arrow survive pointer hiding.')
page += figure('chrome-video-pointer.jpg', 'Chrome video: pointer-like residual beside Open HTML menu survives pointer hiding.')
page += '</div></details><div>'
page += '''</div><p>Native recorded footage also retained a blinking text caret. Chrome isolated video retained a pointer-like automation residual near the HTML-menu button; its cause is still open. Capture configuration cannot be treated as a universal clean-footage guarantee.</p><h2>Child surfaces change the menu result</h2><p>The same native menu disappeared when child inclusion was disabled and appeared when enabled. Its nested submenu was captured too. This is one app/OS combination, not a cross-app guarantee.</p><div class="switch"><button data-image="without" aria-pressed="true">Child inclusion disabled</button><button data-image="with" aria-pressed="false">Child inclusion enabled</button></div>'''
page += f'<figure><img id="menu-image" src="{image("edge-menu-included-window-false.png")}" alt="Native menu omitted with child inclusion disabled"><figcaption id="menu-caption">Menu omitted from the display-bound window capture.</figcaption></figure>'
page += '''<h2>Input delivery beats global focus</h2><p>The destination-aware retest retained <strong>46 key/modifier events</strong> addressed to the fixture. The fixture was foreground for <strong>none of them</strong>. Another 646 events contributed counts only. A focus-only rule would discard legitimate agent input; those outside-scope counts are not a contamination rate.</p><p>All retained events named the current computer-use helper as source, but its zero-valued tags did not identify a durable agent session. Action receipts and uncertainty are still necessary. AX actions can change windows without a pointer event.</p>
<h2>Time and redundancy have useful foundations</h2><table><tr><th>Probe</th><th>Observed result</th><th>What remains</th></tr><tr><td>Frame clock and geometry</td><td>1,178 complete frames. Converted display time and PTS agreed within 1 ns. Screen rect followed an 80-point move.</td><td>Actual action-to-pixel bound; resizing, sleep/wake and display changes.</td></tr><tr><td>Capture callback</td><td>Median lag 0.391 ms; maximum 10.953 ms in this probe.</td><td>Realistic high-motion/load qualification.</td></tr><tr><td>Matched source lanes</td><td>Two 35-second, 1400×964 recordings; zero dropped frames. Isolated footage survived the display crop’s occlusion/move.</td><td>CPU, memory, encoder, thermal and storage budget. About 2.62 MB here is a small static-fixture result.</td></tr><tr><td>Shared computer use</td><td>Native control/typing/selection/menu/cleanup checks and bridge MCP discovery passed. History inventory found 2,555 calls in 32 chats since September 17.</td><td>Historical success audit and a fresh delegated bridge run. Counts/discovery prove neither.</td></tr></table></section>
<section id="strategy"><h2>The proposed service contract</h2><table><tr><th>Owner</th><th>Responsibilities</th></tr><tr><td>Shared computer-use capabilities</td><td>App/provider/version facts; action receipts; delivery evidence; broad canaries plus stable per-app depth lanes; human production expectations.</td></tr><tr><td>Recorder</td><td>Normalized host timeline and geometry segments; explicit child/overlay capture options; source coverage and disturbances; measured recovery/insurance lanes.</td></tr><tr><td>Agent/director</td><td>Intent and rich contextual blocks; semantic relevance refinements with reasons; choice of cost/fidelity and recovery plan.</td></tr><tr><td>Later composition phase</td><td>Cursor/effect recipes, transient reintegration, brief visual/audio cues and final rendering. Deferred here.</td></tr></table><p>Consumers should receive synchronized sources, event/action journals, transforms, context blocks and QA. They should not implement clock calibration or coordinate reconstruction. Verification levels progress from metadata, to sparse source frames, to short previews, to full rendering later.</p><p>Production modes should say whether work is background-cooperative, display-reserved or awaiting an approved interval. Detect interruptions and save the shot; do not block the user prophylactically. P80 estimates need actual measurements. A second display does not isolate every OS shortcut or focus effect.</p></section>
<section id="limits"><h2>The next qualification gates</h2><ol><li>Move context enumeration off the input listener loop; qualify event clocks and pointer coordinates across displays and sleep.</li><li>Depth requalification for Chrome, Electron and other daily apps; verify menu overflow and current helper identities.</li><li>Motion/insurance resource budgets, historical computer-use outcome audit and derivative timeline mapping.</li><li>Safe production delivery at an idle boundary, rollback, loaded-capability readback and final agent runbooks. Visual composition remains next phase.</li></ol><p class="note">The disposable fixture crashed while closing a retained AppKit window. Its lifetime handling was repaired, and closing the occlusion and main windows was verified. One telemetry run spanning the relaunch was discarded. The recorder remained available.</p><p>Chrome native input could not reach its off-Space window even though browser-tab automation worked. Several capture modes also returned SCK -3811 errors. The clean baseline and HTML-menu recording succeeded; native-menu reliability is still unresolved.</p></section>
<details><summary>Read the full implementation strategy and acceptance gates</summary><pre>'''
page += html.escape(strategy)
page += '</pre></details><details><summary>Evidence and repeatable kit</summary><p>Private artifacts: <code>' + html.escape(str(args.evidence)) + '</code></p><p>Source kit: <code>/Users/taylor/src/github/dotfiles/src/record-screen/qualification/</code></p><p>Recorder session: ses_znmm2ude. Recordings: rec_9ysm6u63, rec_329z2bru, rec_pwxrgkwx, rec_cu7uaw6w. Owned fixture, tab, servers and taps were closed/stopped; no active recordings remained.</p></details></main><script>'
page += 'const images=' + __import__('json').dumps({'without': image('edge-menu-included-window-false.png'), 'with': image('edge-menu-included-window-true.png')}) + ';'
page += '''for(const b of document.querySelectorAll('[data-image]'))b.addEventListener('click',()=>{for(const other of document.querySelectorAll('[data-image]'))other.setAttribute('aria-pressed',String(other===b));const shown=b.dataset.image==='with';document.querySelector('#menu-image').src=images[b.dataset.image];document.querySelector('#menu-image').alt=shown?'Native menu present with child inclusion enabled':'Native menu omitted with child inclusion disabled';document.querySelector('#menu-caption').textContent=shown?'Native menu included in the same display-bound window capture.':'Menu omitted from the display-bound window capture.'});</script></html>'''
if '## Pause checkpoint' in Path(__file__).with_name('GATES.md').read_text():
    page = page.replace('<main><nav>', '<main><p class="note"><strong>Paused for Taylor’s call, October 8 at 18:55 UTC.</strong> Owned fixtures and isolated engines are stopped. Production is unchanged. Resume starts with the compiled utility-queue listener candidate; its live qualification is pending.</p><nav>')
args.output.write_text(page)
print(f'Report saved: {args.output} ({args.output.stat().st_size} bytes)')
