#!/usr/bin/env python3
"""Render a private, self-contained evidence report from a supplied probe bundle."""
import argparse
import base64
import html
import mimetypes
import json
from pathlib import Path
from checklist import load_checklist, render_checklist

parser = argparse.ArgumentParser()
parser.add_argument('--evidence', type=Path, required=True)
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()
checklist_data = load_checklist()

def image(name):
    mime = mimetypes.guess_type(name)[0] or 'image/png'
    return 'data:' + mime + ';base64,' + base64.b64encode((args.evidence / name).read_bytes()).decode()

def figure(name, caption):
    return f'<figure><img src="{image(name)}" alt="{html.escape(caption)}"><figcaption>{html.escape(caption)}</figcaption></figure>'

strategy = Path(__file__).with_name('STRATEGY.md').read_text()
page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Capture foundations: live qualification</title>
<style>
:root{color-scheme:light;--ink:#17202b;--paper:#f2f4f6;--line:#c9d3dd;--blue:#24727a;--warn:#805410}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 "Avenir Next",system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:40px 24px 80px}h1{font-size:clamp(30px,5vw,48px);line-height:1.13;max-width:24ch;letter-spacing:-.025em}h2{font-size:27px;margin:48px 0 14px}h3{font-size:19px}p,li{max-width:76ch}a{color:var(--blue)}.lede{font-size:22px;max-width:58ch}nav{display:flex;gap:20px;flex-wrap:wrap}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0}img{width:100%;height:auto;background:#fff;display:block}figcaption{font-size:15px;margin:9px 0 22px}table{border-collapse:collapse;width:100%;font-size:16px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:14px 12px 14px 0}th{color:var(--blue)}button,summary{font:inherit;cursor:pointer}button{padding:10px 16px;color:var(--ink);background:white;border:1px solid var(--line);border-radius:5px}button[aria-pressed=true]{color:white;background:var(--blue)}.switch{display:flex;gap:8px;margin:14px 0}.note{border-left:4px solid var(--warn);padding:10px 18px;background:white}details{margin:24px 0;padding:18px;background:white}summary{font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.65 system-ui,sans-serif}code{font-size:.88em;overflow-wrap:anywhere}:focus-visible{outline:3px solid var(--blue);outline-offset:4px}@media(max-width:650px){main{padding:26px 16px}.pair{grid-template-columns:1fr}table{font-size:14px}th,td{padding-right:8px}}
</style><main><nav><a href="#evidence">View evidence</a><a href="#strategy">Service strategy</a><a href="#limits">Remaining checks</a></nav>
<h1>Capture foundations, tested on your Mac</h1><p class="lede">The source needs three kinds of evidence: what appeared, what received input, and which agent intended the action.</p><p>October 8, 2026. Five staged qualification passes with live source captures and isolated candidate engines. The installed recorder was not changed or restarted. No Claude usage, input lock or new permissions.</p>
<section id="evidence"><h2>Pointer hiding has several layers</h2><p>Both captures below requested pointer hiding. The left still contains computer use’s separate “Software Cursor” window. Excluding that helper app removed it from the display screenshot on the right, while preserving the desktop experience. Streaming exclusion remains a delivery gate.</p><div class="pair">'''
if (args.evidence / 'gates-v2').exists():
    gate_notes = '## Second pass: live evidence' + Path(__file__).with_name('GATES.md').read_text().split('## Second pass: live evidence', 1)[1]
    update = '<section id="second-pass"><h2>Next gates: verified source evidence</h2><p>Live-stream helper exclusion passed, and Chrome’s visible native context menu was captured with child inclusion enabled. A 12-marker series matched every transition: median 8.13 ms, range 3.18–63.52 ms from fixture action handling to captured pixels.</p><p>Across 22 source frames, the candidate geometry transform matched the authored marker within 0.884 pixels through a move and resize. A private source-packet prototype joins relative times, geometry, delivery reasons and an action-block receipt. Raw input positions remain withheld until their coordinate semantics are qualified.</p><div class="pair">'
    update += figure('gates-v2/rect-retry/frame-00000.png', 'Live display stream: software pointer remains despite pointer hiding.')
    update += figure('gates-v2/excluded-retry/frame-00000.png', 'Live stream with verified helper app excluded: software pointer removed.')
    update += '</div><details><summary>Inspect Chrome’s native menu in a live source frame</summary>'
    update += figure('gates-v2/chrome-native-stream/frame-00567.png', 'Visible Chrome menu captured. Provider banner and pointer-like decoration also entered the source; this is not universally clean footage.')
    update += '</details><p class="note">Three concurrent standalone probe starts stalled; sequential retries succeeded. The native menu was absent through the 4.03-second sparse preview and present at 5.04 seconds. These findings require startup bounds and pixel presence checks. Their causes remain open.</p><p>The installed recorder remained unchanged. Concurrent user attribution, cross-display/sleep synchronization, daily-app depth lanes and realistic redundancy budgets still need qualification. Effects and composition remain deferred.</p><details><summary>Read second-pass evidence and remaining gates</summary><pre>' + html.escape(gate_notes) + '</pre></details></section>'
    page = page.replace('<section id="evidence">', update + '<section id="evidence"><p><strong>Initial pass evidence follows.</strong> Second-pass results above supersede its open streaming and visible-Chrome checks.</p>')
if (args.evidence / 'gates-v3/qualification-summary.json').exists():
    third_notes = '## Third pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Third pass:', 1)[1].split('## Second pass: live evidence', 1)[0]
    third = '<section id="third-pass"><h2>Next gates: background contracts and recovery</h2><p>The candidate engine builds and passes 25 target parsing and source-identity checks. Child settings, excluded apps and resolved PIDs now distinguish recording taps and preview lanes. Capability negotiation rejects a legacy engine before it can silently ignore requested options.</p><p>The shared computer-use layer now has four local evidence tools plus a model-free CLI. Two prior app observations and one declared action block were saved and independently read back. Exact version keys, expiry, conflicts, private publication and session scoping are tested.</p><p>A separate qualification supervisor passed synthetic stall, interruption, concurrent admission and recovery tests. It preserves partial evidence and stops only its owned helpers.</p><p class="note">These are source and background checks. The installed recorder remains unchanged. Production SDK routing, engine startup deadlines, automatic receipts, concurrent-user attribution and cross-display/menu/load qualification remain open. No new UI actions or visual composition in this pass.</p><details><summary>Read third-pass scope, evidence and remaining gates</summary><pre>' + html.escape(third_notes) + '</pre></details></section>'
    page = page.replace('<section id="second-pass">', third + '<section id="second-pass">')
if (args.evidence / 'gates-v4/journal-clock-proof.json').exists():
    fourth_notes = '## Fourth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Fourth pass:', 1)[1].split('## Third pass:', 1)[0]
    fourth = '<section id="fourth-pass"><h2>Next gates: signed engine, recovery and source timing</h2><p>The signed isolated engine passed native child-menu inclusion and exclusion, filter-aware preview routing, unavailable-target isolation, scheduled cancellation and recovery after an owned process interruption. The partial MP4 decoded 292 frames; saved manifest counters were stale and now carry a checkpoint warning.</p><p>A bounded recorder-owned journal preserves source frames, geometry segments, encoded and held-frame references, exact host times and declared marks. Live tests caught two timing problems: a default 600-tick video track and a separately quantized movie offset. Setting both timescales corrected them.</p><p><strong>All 1,337 encoded samples matched journal timestamps exactly</strong> across the corrected H.264 and Retina HEVC takes. The HEVC marker matched all three geometry segments within 0.884 pixels through movement and resizing. Both journals closed with zero reported telemetry loss.</p><div class="pair">'
    fourth += figure('gates-v4/encoded-menu.png', 'Actual encoded source footage preserved the native edge menu; app-painted arrow remains.')
    fourth += figure('gates-v4/hevc-proof-geometry-2.png', 'Actual Retina HEVC frame after resizing. Journal transform predicted marker edges within 0.884 pixels.')
    fourth += '</div><p class="note">Production still runs the original engine. These are bounded candidate/fixture results, not a universal app, cross-display, physical-input latency or resource guarantee. Input attribution, native action receipts, daily-app depth, collision/load gates and safe delivery remain open. Visual composition remains deferred.</p><details><summary>Read fourth-pass evidence, corrections and limits</summary><pre>' + html.escape(fourth_notes) + '</pre></details></section>'
    page = page.replace('<section id="third-pass">', fourth + '<section id="third-pass">')
if (args.evidence / 'gates-v5/final-input-proof.json').exists():
    fifth_notes = '## Fifth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Fifth pass:', 1)[1].split('## Fourth pass:', 1)[0]
    fifth = '<section id="fifth-pass"><h2>Next gates: scoped input and contextual actions</h2><p><strong>All 36 native key/modifier events matched delivered-event evidence; none required fixture foreground.</strong> A separate owned app received 40 key events, with zero addressed keys retained in the source after the action block closed. Outside-scope activity contributed counts only.</p><p>Recorder-stamped action blocks preserve intent, contextual detail and delivery uncertainty. The AX marker below changed inside its declared interval while another owned app covered the target. No mouse event was fabricated for that accessibility action.</p><div class="pair">'
    fifth += figure('gates-v5/input-marker-before.png', 'Encoded source before the declared AX action: red marker.')
    fifth += figure('gates-v5/input-marker-after.png', 'Encoded source after the AX action: green marker; app-painted arrow remains.')
    fifth += '</div><p>Real candidate restart preserved an interrupted block with unknown end time. Wrong callers were rejected, and the supported callback wrapper stored a rich shared receipt without replaying an operation. The final signed candidate matched eight more delivered keys, rejected five malformed requests, and returned its passive listener to inactive. Both new takes closed with zero telemetry loss; all 3,244 muxed video timestamps matched the source journals exactly.</p><p class="note">Production remains the original signed engine. Raw pointer coordinates and event-clock mapping remain unqualified. Context enumeration averaged 11.66 ms and peaked at 41.50 ms on the listener loop; move it off that loop before production latency/load recommendations. Secure input, tap faults, other providers, daily-app depth, cross-display/sleep and motion/insurance budgets remain open.</p><details><summary>Inspect fifth-pass evidence, corrections and limits</summary><pre>' + html.escape(fifth_notes) + '</pre></details></section>'
    page = page.replace('<section id="fourth-pass">', fifth + '<section id="fourth-pass">')
if (args.evidence / 'gates-v6/qualification-summary.json').exists():
    page = page.replace('<nav>', '<nav><a href="#sixth-pass">Latest qualification</a>', 1)
    sixth_notes = '## Sixth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Sixth pass:', 1)[1].split('## Fifth pass:', 1)[0]
    sixth = '<section id="sixth-pass"><h2>Sixth pass: displays, protected input and desktop recovery</h2><p>The background context sampler passed 113 blocked-query and lifecycle checks. Live main-loop refresh cost averaged 2.20 ms before the desktop failure, compared with 11.66 ms when it also enumerated windows. These are component costs, not guaranteed input latency.</p><p>The owned fixture moved from built-in Retina to the external display with a negative desktop origin, then returned. Four encoded marker frames matched their own geometry transforms exactly; 8,315 muxed timestamps and 24 delivered key/modifier events matched their source records.</p><div class="pair">'
    sixth += figure('gates-v6/cross-display-pixels-geometry-8.png', 'Built-in Retina: marker edges match the 2× transform.')
    sixth += figure('gates-v6/cross-display-pixels-geometry-41.png', 'External display: 1× content on the fixed encoded canvas; negative desktop origin maps correctly.')
    sixth += '</div><p>Explicit protected input produced enabled/ended gaps, omitted all 24 delivered protected events, then recovered six normal events. The secure field alone did not enable global protection for the injected provider. A healthy listener cannot establish complete keyboard coverage.</p><p><strong>A real WindowServer exit interrupted the Chrome take.</strong> Its cause is unknown. Partial video decoded 1,197 frames across 42.02 seconds, while the complete journal contained 1,210 accepted encoder submissions. The failed proof is retained. New source descriptors distinguish journal closure from video finalization; recovery must measure actual decodable coverage.</p><p>The surviving test engine bounded an unfinished SDK discovery at three seconds and refused a retry in 0.448 ms while keeping status/action recovery available. A fresh signed isolated process recovered and completed a Chrome take with 1,732 exact muxed timestamps and zero journal loss.</p><div class="pair">'
    sixth += figure('gates-v6/chrome-html-source.jpg', 'Actual encoded Chrome source includes the HTML menu; a pointer-like residual remains.')
    sixth += figure('gates-v6/chrome-native-source.jpg', 'Actual encoded source includes the genuine native context menu with child capture enabled.')
    sixth += '</div><p class="note">Browser-provider typing changed DOM text without app-addressed OS keyboard evidence. Bounded action candidates addressed to Codex remain uncertain. Production is still the original signed engine. Electron depth, raw pointer coordinates, sleep, exclusion lifetimes, realistic resource budgets, derivative mapping and release remain open.</p><details><summary>Inspect sixth-pass evidence and limits</summary><pre>' + html.escape(sixth_notes) + '</pre></details></section>'
    page = page.replace('<section id="fifth-pass">', sixth + '<section id="fifth-pass">')
if (args.evidence / 'gates-v7/qualification-summary.json').exists():
    page = page.replace('<a href="#sixth-pass">Latest qualification</a>', '<a href="#seventh-pass">Latest qualification</a>')
    seventh_notes = '## Seventh pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Seventh pass:', 1)[1].split('## Sixth pass:', 1)[0]
    seventh = '<section id="seventh-pass"><h2>Electron depth and a failed motion-insurance gate</h2><p><strong>The user-supplied WindowServer report shows a second desktop failure.</strong> At 20:51:55 UTC, its watchdog reported an unresponsive main thread and a 40-second missed check-in. Kernel image UUIDs in that thread match Apple’s IOGPUFamily and AGXG17X graphics drivers. This establishes a graphics wait, not the responsible workload or root cause.</p><p>Owned fixtures and the idle isolated test engine are stopped. Production automatically recovered on its original signed build, with its existing screen grant. No new candidate has been installed. Further live load waits on passive incident and health reconciliation.</p><div class="pair">'
    seventh += figure('gates-v7/electron-child-false.jpg', 'Actual Electron source: context menus absent with child inclusion disabled.')
    seventh += figure('gates-v7/electron-child-true.jpg', 'Actual Electron source: all three native menu levels captured with child inclusion enabled.')
    seventh += '</div><p>Five Electron takes supplied 5,002 exact muxed timestamps. All 98 retained key/modifier events were addressed to Code, while actor ownership remains unknown. The padded display pair contained the menus and unrelated desktop content; it did not prove additional visible menu rows beyond the isolated canvas.</p><p>Two 25-second single-window motion takes passed exact source/mux checks: 721 samples at point resolution and 1,384 at Retina resolution. The decoded app counter changed 719 and 1,337 times. Recorder CPU medians were 2.02% and 5.94% of one core, with sampled RSS peaks of 89.23 and 149.28 MiB. These measurements exclude attributable GPU/driver cost and do not establish production capacity.</p>'
    seventh += figure('gates-v7/motion-source.jpg', 'Authored motion source with a binary app counter; no physical-presentation or timer-to-video latency claim.')
    seventh += '<p class="note">The paired window/display take remains failed. Its window video decoded 713 packets versus 715 submissions, failed timestamp correspondence, and showed a constant app counter. The display source finalized with 379 exact samples, but matching scene coverage was not established while the window was off Space. A finalized backup is not proof of a recoverable shot.</p><p>During the failure, periodic listener context blocked for 63 seconds and a Quartz query for 68 seconds. The recording’s stop was delayed. The next source candidate moves periodic TCC/workspace/tap reads and shared recording disturbance checks to retained, bounded background workers. It compiled and signed; 113 listener, 106 recording-monitor and 113 window-query lifecycle checks passed. It awaits a fresh live canary.</p><p>A structural audit found matching results for 2,655 CUA calls across 31 historical chats. Observation references accompanied 1,441 of 1,510 scripts with action references in the same or next call. Opaque outputs and static references do not prove task success; structured delivery, verification and cleanup receipts remain necessary.</p><details><summary>Inspect seventh-pass evidence and limits</summary><pre>' + html.escape(seventh_notes) + '</pre></details></section>'
    page = page.replace('<section id="sixth-pass">', seventh + '<section id="sixth-pass">')
if (args.evidence / 'gates-v8/qualification-summary.json').exists():
    summary8 = json.loads((args.evidence / 'gates-v8/qualification-summary.json').read_text())
    page = page.replace('<a href="#seventh-pass">Latest qualification</a>', '<a href="#eighth-pass">Latest qualification</a>')
    page = page.replace('Five staged qualification passes', 'Eight staged qualification passes')
    notes8 = '## Eighth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Eighth pass:', 1)[1].split('## Historical clean pause', 1)[0]
    eighth = '<section id="eighth-pass"><h2>Mapped previews and recovered context workers</h2><p>Taylor explicitly resumed. After the pressure incident closed and paging/churn fell, the signed isolated candidate completed a 22-second native take. <strong>All 639 muxed timestamps matched the source journal exactly, and four typed key transitions matched native delivery timestamps.</strong> Periodic OS context ran in background workers; main refresh averaged 24.7 microseconds. This is a component result, not physical-input latency.</p><p>Exports now carry their own actual media clock, parent frame references and scale map. Draft/standard/full select cost and fidelity, with width/fps/backend overrides. The service maps exact parent offsets into saved previews—including GIF centisecond rounding—and explicitly excludes times outside the clip. Existing engines refuse the new contract rather than ignore it.</p>'
    eighth += figure('gates-v8/live-preview-gif-menu.png', 'Actual mapped GIF preview preserves the native edge menu and green marker. The app-painted arrow remains; transient overflow and visual composition are separate gates.')
    eighth += '<p>Ten authored software exports matched 264 decoded frames to expected held parent content, including a nonzero source start. The first differential GIF palette lost its final color despite correct packet counts; full histograms corrected the pixel test. Failed output is retained. A final repeat matched another 139 frames across six exports; 35 assertions passed. Decimal grid arithmetic corrected a one-frame shift at 0.07 seconds, and an actual native-source export verified seven packets from ticks 7 to 14.</p><p>Three real previews each had 145 verified parent references. Full/native/60-fps hardware output added 725 references with exact nominal timestamps. Real MCP source/time-map readback passed. That pass’s final signed candidate <code>' + html.escape(summary8['loaded_latest_build']) + '</code> loaded, and repeated draft requests produced distinct immutable names. 88 owned-subprocess checks and ten Node regressions passed.</p><p class="note">Production remains the original build. The action close arrived after its deadline and correctly stayed expired; delivery/pixel evidence is separate. All owned capture, fixture, export and input workers are stopped, with private evidence copied out of temporary runtime storage. Helper PID churn, pointer/tap/sleep limits, remaining overflow, motion insurance, safe installation/rollback and final runbooks remain open. Visual effects remain deferred.</p><details><summary>Read eighth-pass evidence and remaining gates</summary><pre>' + html.escape(notes8) + '</pre></details></section>'
    page = page.replace('<section id="seventh-pass">', eighth + '<section id="seventh-pass">')
if (args.evidence / 'gates-v9/qualification-summary.json').exists():
    summary9 = json.loads((args.evidence / 'gates-v9/qualification-summary.json').read_text())
    page = page.replace('<a href="#eighth-pass">Latest qualification</a>', '<a href="#ninth-pass">Latest qualification</a>')
    page = page.replace('Eight staged qualification passes', 'Nine staged qualification passes')
    notes9 = '## Ninth pass:' + Path(__file__).with_name('GATES.md').read_text().split('## Ninth pass:', 1)[1].split('## Eighth pass:', 1)[0]
    ninth = '<section id="ninth-pass"><h2>Excluded-helper lifetime and recovery</h2><p>A background helper can relaunch under a new process ID while an existing filter still refers to its predecessor. The candidate now watches application identities and interrupts the take on an observed change, preserving partial video and explicit uncertainty.</p><p>The live test kept running when an unrelated fixture opened and closed. Closing the excluded LSUIElement helper interrupted the take and finalized its partial video. A fresh take resolved the relaunched helper’s new PID and completed. <strong>All 661 muxed timestamps matched the three source journals exactly.</strong> The sampled baseline contained 63,140 authored magenta pixels; excluded and recovered samples contained zero.</p><p>The first implementation misread an indexed app-list change as a complete snapshot and refused startup. Full-list reads corrected it; failed evidence remains available. 35 mechanical checks and ten Node regressions passed. Recording source and a 12-frame exported preview retained uncertain parent quality. MCP rejects a filter-only engine lacking the new lifetime capability.</p><p class="note">Observation follows the main run loop and may lag: the first affected pixel stays unknown. Persistent preview lanes, capture-color fidelity, pointer/tap/sleep limits, remaining overflow, insurance/admission and production delivery remain open. Installed production is unchanged. Owned helper and engines are stopped; peer workflows were preserved.</p><details><summary>Read ninth-pass evidence and remaining gates</summary><pre>' + html.escape(notes9) + '</pre></details></section>'
    page = page.replace('<section id="eighth-pass">', ninth + '<section id="eighth-pass">')
if (args.evidence / 'gates-v10/qualification-summary.json').exists():
    summary10 = json.loads((args.evidence / 'gates-v10/qualification-summary.json').read_text())
    page = page.replace('<a href="#ninth-pass">Latest qualification</a>', '<a href="#tenth-pass">Latest qualification</a>')
    page = page.replace('Nine staged qualification passes', 'Ten staged qualification passes')
    notes10 = Path(__file__).with_name('GATES.md').read_text().split('## Tenth pass:', 1)[1].split('## Ninth pass:', 1)[0]
    tenth = '<section id="tenth-pass"><h2>Preview recovery, pointer alignment and a color finding</h2><p>The resumed stage carried earlier evidence forward. Candidate <code>' + html.escape(summary10['loaded_build']) + '</code> retires an excluded preview lane when its helper changes identity, rejects a request while the helper is absent, and resolves a fresh lane after relaunch. The unrelated lane remained available. Fifteen mechanical checks and two targeted MCP tests passed.</p><p>One combined fixture take supplied <strong>481 exact source/mux timestamps</strong> and four app-delivered native clicks across 1×/2× displays. Raw coordinates and event timestamps matched the app exactly; all four predicted marker positions matched actual video within <strong>0.5 pixels</strong>. Initial native delivery refused; an exposed move control recovered it, and the same take was kept. Requested screenshot coordinates were not assumed equal to delivered points.</p><p class="note"><strong>Cross-display color fidelity needs correction.</strong> Six declared sRGB references differed by at most two channel values on Retina, but by as much as 76 on the external display. Returning home restored the initial values. Capture already requests sRGB; the actual buffer metadata/pixel format and writer conversion need isolation before choosing a fix. The software preview reproduced all 18 sampled parent RGB values exactly, including the inaccurate colors.</p><div class="pair">'
    tenth += figure('gates-v10/colors-0.png', 'Actual source at Retina scale: declared sRGB patches differed by at most two 8-bit channel values.')
    tenth += figure('gates-v10/colors-1.png', 'Same authored source on the external display: primaries shifted; maximum channel error 76.')
    tenth += '</div><p>Owned fixtures and engines exited with no input subscribers, preview lanes, exclusion leases or pending exports. Production remains unchanged. The checklist records preview lifetime as completed for its candidate scope, pointer/provider mapping as partial, and color fidelity as needing retest. No universal provider, clean-footage, sleep or production-release claim follows from these checks.</p><details><summary>Read tenth-pass evidence and the next narrow checks</summary><pre>' + html.escape(notes10) + '</pre></details></section>'
    page = page.replace('<section id="ninth-pass">', tenth + '<section id="ninth-pass">')
if (args.evidence / 'gates-v11/qualification-summary.json').exists():
    summary11 = json.loads((args.evidence / 'gates-v11/qualification-summary.json').read_text())
    page = page.replace('<a href="#tenth-pass">Latest qualification</a>', '<a href="#eleventh-pass">Latest qualification</a>')
    page = page.replace('Ten staged qualification passes', 'Eleven staged qualification passes')
    notes11 = Path(__file__).with_name('GATES.md').read_text().split('## Eleventh pass:', 1)[1].split('## Tenth pass:', 1)[0]
    eleventh = '<section id="eleventh-pass"><h2>Color backing isolated; observed tags captured</h2><p>Eight single-buffer probes showed the external-display shift before video encoding, in both BGRA and NV12. An explicit 709 matrix and sRGB conversion did not repair it. Actual display-profile transforms closely matched the shifted primaries. Changing only the owned fixture’s backing store to declared sRGB restored its references within one channel value.</p><p>Candidate <code>' + html.escape(summary11['loaded_build']) + '</code> now records actual pixel-format and color-tag boundaries. Source metadata keeps requested sRGB separate from observed tags; missing values remain unknown. Ten mechanical checks and actual MCP readback passed.</p><p><strong>The declared-backing recording passed:</strong> 229 exact muxed/source timestamps, three external/Retina/external geometry segments, no encoder or journal loss, and 18 sampled colors within two channel values. Its 230-frame software preview reproduced all 18 source RGB values exactly.</p><div class="pair">'
    eleventh += figure('gates-v11/external-observed-bgra/ci-srgb.png', 'Inherited external backing: shifted source references remain preserved as evidence.')
    eleventh += figure('gates-v11/encoded-colors-0.png', 'Declared sRGB backing: actual encoded external-display reference path passed within two channel values.')
    eleventh += '</div><p class="note">The controlled backing experiment identifies the local boundary; it does not justify a recorder-wide correction, another app’s color-space change, or a physical/HDR accuracy promise. Preserve app backing behavior and qualify the relevant app lane. The original failure and successful pointer evidence remain intact. All owned processes exited; production is unchanged.</p><p>API references: <a href="https://developer.apple.com/documentation/screencapturekit/scstreamconfiguration/colorspacename">capture output color space</a> and <a href="https://developer.apple.com/documentation/appkit/nswindow/colorspace">window backing color space</a>.</p><details><summary>Read eleventh-pass evidence and remaining limits</summary><pre>' + html.escape(notes11) + '</pre></details></section>'
    page = page.replace('<section id="tenth-pass">', eleventh + '<section id="tenth-pass">')
if (args.evidence / 'gates-v12/qualification-summary.json').exists():
    summary12 = json.loads((args.evidence / 'gates-v12/qualification-summary.json').read_text())
    notes12 = Path(__file__).with_name('GATES.md').read_text().split('## Twelfth pass:', 1)[1].split('## Eleventh pass:', 1)[0]
    page = page.replace('<a href="#eleventh-pass">Latest qualification</a>', '<a href="#twelfth-pass">Latest qualification</a>')
    twelfth = '<section id="twelfth-pass"><h2>Clock gaps stop the affected take</h2><p>Bracketed uptime and continuous samples now make uncertain clock intervals explicit. The first live test exposed a valid interval crossing zero; signed bounds corrected it. Twenty-six clock checks, 100 awake samples and 125 journal-bound checks passed.</p><p>The service interrupts the affected take, preserves partial footage and suppresses held end frames through the uncertain interval. Ten actual arming-state checks retained unfinished admission, left a peer intact and prevented late resurrection. Latest signed, privately loaded candidate: <code>' + html.escape(summary12['loaded_latest_build']) + '</code>.</p><table><tr><th>Source check</th><th>Verified result</th><th>Limit</th></tr><tr><td>Awake source and MCP</td><td>81 exact muxed timestamps; nine anchors over 8.16 seconds; no clock gaps or lost rows; actual MCP policy readback.</td><td>87 callbacks from a static fixture; no independent sparse-callback or wake proof.</td></tr><tr><td>Injected gap during real capture</td><td>One gap interrupted the take; 33 exact timestamps; partial finalization; zero lost rows and zero held-at-end fill.</td><td>Controlled continuous-clock offset, not physical sleep.</td></tr></table><p class="note">Sleep/wake stays partial. Physical sleep, provider clock equivalence and sub-threshold changes remain unqualified. Receipt segments do not remap frame PTS or raw provider timestamps. The active capture used the frozen implementation before a final early-arm guard; the final guard passed the arming checks and exact loaded readback. Production is unchanged; all owned processes exited.</p><p>Clock API references: <a href="https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time">uptime</a> and <a href="https://developer.apple.com/documentation/kernel/1646199-mach_continuous_time">continuous time</a>.</p><details><summary>Read twelfth-pass evidence and limits</summary><pre>' + html.escape(notes12) + '</pre></details></section>'
    page = page.replace('<section id="eleventh-pass">', twelfth + '<section id="eleventh-pass">')
if (args.evidence / 'gates-v13/qualification-summary.json').exists():
    summary13 = json.loads((args.evidence / 'gates-v13/qualification-summary.json').read_text())
    notes13 = Path(__file__).with_name('GATES.md').read_text().split('## Thirteenth pass:', 1)[1].split('## Twelfth pass:', 1)[0]
    page = page.replace('<a href="#twelfth-pass">Latest qualification</a>', '<a href="#thirteenth-pass">Latest qualification</a>')
    thirteenth = '<section id="thirteenth-pass"><h2>Tap faults preserve app input and expose missing telemetry</h2><p>The candidate now limits timeout recovery to three attempts using fresh background permission observations. User-disable, exhaustion and observed revocation block automatic restart while subscriptions remain. Only the recorder’s passive tap is retired; app input stays available.</p><p><strong>Eight native delivered key transitions supplied exact evidence:</strong> four were omitted while exhausted or user-disabled; four matched the source journal after deliberately recreating the listener. A second subscriber did not revive the user-disabled lifecycle. Actor ownership remains unknown.</p><p>Twenty-seven policy checks, ' + str(summary13['input_summary_checks']) + ' notification-summary checks and 125 journal checks passed. Source descriptors now persist bounded gap counts and the latest accepted listener/policy notification, including negative faults replacing an older listening state. Latest signed, privately loaded candidate: <code>' + html.escape(summary13['loaded_latest_build']) + '</code>.</p><p class="note">Timeout notifications were controlled. A 750-ms passive callback delay produced no natural SDK timeout; physical TCC revocation remains untested. Initial CG, per-key protection and recovery calls are not fully bounded. Summaries describe accepted notifications, not live health or complete coverage. No security setting or global protected-input mode was changed. All owned processes exited; installed production is unchanged.</p><details><summary>Read thirteenth-pass evidence and limits</summary><pre>' + html.escape(notes13) + '</pre></details></section>'
    page = page.replace('<section id="twelfth-pass">', thirteenth + '<section id="twelfth-pass">')
if (args.evidence / 'gates-v14/qualification-summary.json').exists():
    summary14 = json.loads((args.evidence / 'gates-v14/qualification-summary.json').read_text())
    notes14 = Path(__file__).with_name('GATES.md').read_text().split('## Fourteenth pass:', 1)[1].split('## Thirteenth pass:', 1)[0]
    page = page.replace('<a href="#thirteenth-pass">Latest qualification</a>', '<a href="#fourteenth-pass">Latest qualification</a>')
    page = page.replace('Eleven staged qualification passes', 'Fourteen staged qualification passes')
    fourteenth = '<section id="fourteenth-pass"><h2>Padded capture preserves a popup beyond the original frame</h2><p>Two sequential native takes passed <strong>102 exact muxed/source timestamps</strong>, without dropped encoder frames or lost journal rows. A supplied 190×58 popup crop extends 140 points right and 28 down beyond the original window. Its recorded position matched an independent screenshot at zero spatial offset.</p><p>The verifier saves the actual decoded sample, exact video-relative time and global position. Rechecking the retained evidence passed. The image below contains only the authored popup; unrelated display pixels stay private.</p>'
    fourteenth += figure('gates-v14/retained-overflow-spatial-proof.menu.png', 'Actual encoded native popup crop. Its bounded region extends beyond the original window; this is a source layer, not a final composite.')
    fourteenth += '<p><strong>The display take lost the base window to occlusion while preserving the popup.</strong> This supports a separately cropped transient layer. It does not prove synchronized whole-shot insurance; that gate remains open.</p><p>Chrome native-select readiness also remains open. Isolated capture could see an owned fixture while display capture showed it covered, despite on-screen metadata. Native pointer delivery refused, and browser focus did not establish the popup. This scoped unknown was stored in shared computer-use facts and independently read back exactly.</p><p class="note">This is one authored region at 1× scale and one geometry segment. Deeper menus, automatic segmentation, popup ownership and simultaneous base/overflow coverage remain unqualified. All owned tabs, fixture, server and candidate engine exited. Installed production remains unchanged.</p><details><summary>Read fourteenth-pass evidence and remaining boundaries</summary><pre>' + html.escape(notes14) + '</pre></details></section>'
    page = page.replace('<section id="thirteenth-pass">', fourteenth + '<section id="thirteenth-pass">')
if (args.evidence / 'gates-v15/qualification-summary.json').exists():
    summary15 = json.loads((args.evidence / 'gates-v15/qualification-summary.json').read_text())
    notes15 = Path(__file__).with_name('GATES.md').read_text().split('## Fifteenth pass:', 1)[1].split('## Fourteenth pass:', 1)[0]
    page = page.replace('<a href="#fourteenth-pass">Latest qualification</a>', '<a href="#fifteenth-pass">Latest qualification</a>')
    page = page.replace('Fourteen staged qualification passes', 'Fifteen staged qualification passes')
    fifteenth = '<section id="fifteenth-pass"><h2>A stalled take no longer triggers a service restart</h2><p>The candidate isolates a finalization deadline to the affected recording and keeps its capacity reservation until outstanding work settles. Its journal closes with failed video finalization and unverified coverage while the recording queue is blocked. A late callback cannot change the interrupted take to done or start a review.</p><p><strong>26 controlled checks passed</strong> with authored off-screen frames through the actual writer and recording code. The healthy peer finished while the affected queue stayed blocked. Callback completion alone did not release a still-blocked encoder call. Another 27 startup, clock and admission checks passed; independent decoding matched all 15 packet timestamps.</p><p>Signed private candidate <code>' + html.escape(summary15['loaded_build']) + '</code> reported its exact build and new capability. It exited cleanly. The installed production engine is still unchanged.</p><p class="note">This proves controlled failure handling, not a natural hardware hang or hardware-level isolation. Unconfirmed stream stops retain admission; that SDK fault lane and initial OS calls remain open. Host pressure stayed warning. The configured budget of 16 is not a capacity guarantee, and production delivery remains pending.</p><details><summary>Read fifteenth-pass evidence and limits</summary><pre>' + html.escape(notes15) + '</pre></details></section>'
    page = page.replace('<section id="fourteenth-pass">', fifteenth + '<section id="fourteenth-pass">')
if (args.evidence / 'gates-v16/qualification-summary.json').exists():
    summary16 = json.loads((args.evidence / 'gates-v16/qualification-summary.json').read_text())
    notes16 = Path(__file__).with_name('GATES.md').read_text().split('## Sixteenth pass:', 1)[1].split('## Fifteenth pass:', 1)[0]
    page = page.replace('<a href="#fifteenth-pass">Latest qualification</a>', '<a href="#sixteenth-pass">Latest qualification</a>')
    page = page.replace('Fifteen staged qualification passes', 'Sixteen staged qualification passes')
    sixteenth = '<section id="sixteenth-pass"><h2>Stream stops now report acknowledgment and uncertainty</h2><p>The candidate distinguishes running, overdue, acknowledged and returned-error stops. A diagnostic deadline does not retry, cancel SDK work or release its reservation. Late acknowledgment releases it; a returned error stays unconfirmed and reserved.</p><p><strong>25 controlled checks passed</strong> through actual recording and admission code. A tiny passive canary then received a real successful stop acknowledgment, matched both static/held packet timestamps and returned unfinished work to zero. Signed private candidate <code>' + html.escape(summary16['loaded_build']) + '</code> exited cleanly; production remains unchanged.</p><p>The read-only delivery inventory found the installed engine visibly idle and signing identities matched. Legacy unfinished-work diagnostics remain unknown, and the observation does not fence new admissions. No backup, installation or restart occurred.</p><p class="note">Natural stop failures, backend resource release, full-shot insurance and capacity remain unqualified. Next: guarded idle delivery and preserved bundle/state preparation, followed by installed consumer smoke tests.</p><details><summary>Read sixteenth-pass evidence and limits</summary><pre>' + html.escape(notes16) + '</pre></details></section>'
    page = page.replace('<section id="fifteenth-pass">', sixteenth + '<section id="fifteenth-pass">')
if (args.evidence / 'gates-v17/qualification-summary.json').exists():
    summary17 = json.loads((args.evidence / 'gates-v17/qualification-summary.json').read_text())
    notes17 = Path(__file__).with_name('GATES.md').read_text().split('## Seventeenth pass:', 1)[1].split('## Sixteenth pass:', 1)[0]
    page = page.replace('<a href="#sixteenth-pass">Latest qualification</a>', '<a href="#seventeenth-pass">Latest qualification</a>')
    page = page.replace('Sixteen staged qualification passes', 'Seventeen staged qualification passes')
    section17 = '<section id="seventeenth-pass"><h2>Maintenance now reserves engine admission</h2><p>The candidate fences new capture and mutation work before checking existing jobs. Active and scheduled peers block maintenance. Expiry releases the lease without restarting; a checked restart commitment pins the fence until actual exit. Human input stays available.</p><p><strong>25 native checks, five client tests and 14 authored build checks passed.</strong> The private protocol refused a scheduled peer and new work under a lease, validated its PID/token, then exited once through authorized maintenance. Signed candidate <code>' + html.escape(summary17['loaded_build']) + '</code> and its exact capabilities were read back.</p><p>CLI and installer entry points are guarded. A final expired lease retains the compiled artifact for reuse; prior-bundle copies are verified before replacement. Production remains on its original build.</p><p class="note">Real bundle/state preservation, first legacy delivery and installed consumers remain next. The legacy first upgrade uses explicit observed idle checks and is unfenced; it cannot inherit candidate guarantees. These guards cover engine RPC admissions, not cross-service isolation or user-input locking.</p><details><summary>Read seventeenth-pass evidence and limits</summary><pre>' + html.escape(notes17) + '</pre></details></section>'
    page = page.replace('<section id="sixteenth-pass">', section17 + '<section id="sixteenth-pass">')
if (args.evidence / 'gates-v18/qualification-summary.json').exists():
    summary18 = json.loads((args.evidence / 'gates-v18/qualification-summary.json').read_text())
    notes18 = Path(__file__).with_name('GATES.md').read_text().split('## Eighteenth pass:', 1)[1].split('## Seventeenth pass:', 1)[0]
    page = page.replace('<a href="#seventeenth-pass">Latest qualification</a>', '<a href="#eighteenth-pass">Latest qualification</a>')
    page = page.replace('Seventeen staged qualification passes', 'Eighteen staged qualification passes')
    section18 = '<section id="eighteenth-pass"><h2>Capture foundations are installed; broader qualification continues</h2><p>Production now runs <code>' + html.escape(summary18['build']) + '</code> with its existing screen grant. The first legacy upgrade used explicit idle observations, preserved a verified prior bundle and six state files, and reused the tested signed artifact. A subsequent fenced restart preserved history; all six prior state hashes still match.</p><p><strong>Installed consumers passed their passive smoke scope:</strong> two exact source/mux timestamps, zero journal loss and ten exact decoded draft packets. Source, export time map, history and actual connector readback passed. Owned session and servers are closed, with no unfinished capture, input subscriber or maintenance lease.</p><p>The smoke observer failed after restart. Readback recovered existing work without another capture, export or restart. Live same-MCP reconnect remains unverified. A synthetic disconnect test verified read recovery and single mutation submissions; new adapter 0.8.0 reports its loaded no-replay policy.</p><p class="note">The existing harness adapter does not report that new policy; native installation alone does not reload MCP JavaScript. Verify consumers at their next safe launch. Restoration, broader apps/input, motion insurance, resources and physical sleep remain open. No live rollback or user-input lock was used; visual composition remains deferred.</p><details><summary>Read eighteenth-pass evidence, observer corrections and limits</summary><pre>' + html.escape(notes18) + '</pre></details></section>'
    page = page.replace('<section id="seventeenth-pass">', section18 + '<section id="seventeenth-pass">')
if (args.evidence / 'gates-v19/qualification-summary.json').exists():
    summary19 = json.loads((args.evidence / 'gates-v19/qualification-summary.json').read_text())
    notes19 = Path(__file__).with_name('GATES.md').read_text().split('## Nineteenth pass:', 1)[1].split('## Eighteenth pass:', 1)[0]
    page = page.replace('<a href="#eighteenth-pass">Latest qualification</a>', '<a href="#nineteenth-pass">Latest qualification</a>')
    page = page.replace('Eighteen staged qualification passes', 'Nineteen staged qualification passes')
    section19 = '<section id="nineteenth-pass"><h2>Input loss now preserves receipt order and scope continuity</h2><p><strong>Thirty controlled checks passed through the actual input queues.</strong> The queue stayed capped at 2,048 events, reported 2,001 lost callbacks after earlier accepted samples, and invalidated a drag whose release was lost. A subsequent outside drag was excluded; a fresh in-scope sample stayed usable. A joining recording inherited no earlier loss, and a final gap remained visible without another accepted callback.</p><p>The journal closed with zero lost rows while separately reporting input callback loss. Exact callback/receipt frontiers and bounded type counts are retained; no omitted positions, codes or actors are invented.</p><p>Signed build <code>' + html.escape(summary19['loaded_build']) + '</code> is now installed with its existing grant. One fenced build reused the tested artifact. The same MCP 0.8.0 process read the new build and retained source across native restart; all twelve preserved state files survived. No additional capture or observer retry was used.</p><p class="note">The burst used authored scalar samples, not a physical event source. Native drag/scroll, provider rates, same-app actor distinction, initial OS calls, precise listener-start coverage and existing consumer migration remain open. Production journal capacity stays 64; the test used 4096 to isolate ingress loss. Visual composition remains deferred.</p><details><summary>Read nineteenth-pass evidence, delivered scope and next gates</summary><pre>' + html.escape(notes19) + '</pre></details></section>'
    page = page.replace('<section id="eighteenth-pass">', section19 + '<section id="eighteenth-pass">')
if (args.evidence / 'gates-v20/qualification-summary.json').exists():
    summary20 = json.loads((args.evidence / 'gates-v20/qualification-summary.json').read_text())
    notes20 = Path(__file__).with_name('GATES.md').read_text().split('## Twentieth pass:', 1)[1].split('## Nineteenth pass:', 1)[0]
    page = page.replace('<a href="#nineteenth-pass">Latest qualification</a>', '<a href="#twentieth-pass">Latest qualification</a>')
    page = page.replace('Nineteen staged qualification passes', 'Twenty staged qualification passes')
    section20 = '<section id="twentieth-pass"><h2>Native gestures: pixels verified; installed input grant pending</h2><p>The authored native canvas received down, two drags, up and wheel. Independent AppKit-to-Quartz coordinates matched raw CG points. The retained video placed the drag endpoint within <strong>0.45 pixels</strong> and the scroll stripe within <strong>0.04 pixels</strong>. Initial native screenshot refusal recovered through the observed Raise action; the same fixture and footage were kept.</p><p>Two existing takes supplied <strong>398 and 307 exact source/mux timestamps</strong> with zero encoder or journal loss. The recovered action bracket closed promptly as delivered; the first expired bracket remains interrupted. Sparse CUA gestures do not prove physical event density or touchpad phases.</p><p class="note"><strong>Screen Recording and Input Monitoring are separate grants.</strong> Installed production has the former but currently lacks the latter. Both input-enabled takes explicitly reported missing access and retained no input events. Taylor approved enabling the signed installed recorder; System Settings is awaiting human Touch ID before adding it. No grant or telemetry recovery has been claimed. A fresh app-delivered canary is next; no restart or repeat of settled footage checks.</p><details><summary>Read twentieth-pass evidence and remaining input gates</summary><pre>' + html.escape(notes20) + '</pre></details></section>'
    page = page.replace('<section id="nineteenth-pass">', section20 + '<section id="nineteenth-pass">')
if (args.evidence / 'gates-v21/qualification-summary.json').exists():
    summary21 = json.loads((args.evidence / 'gates-v21/qualification-summary.json').read_text())
    notes21 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-first pass:', 1)[1].split('## Twentieth pass:', 1)[0]
    page = page.replace('<a href="#twentieth-pass">Latest qualification</a>', '<a href="#twenty-first-pass">Latest qualification</a>')
    page = page.replace('Twenty staged qualification passes', 'Twenty-one staged qualification passes')
    section21 = '<section id="twenty-first-pass"><h2>Private fallback and forward restoration passed</h2><p>The actual signed current and preserved previous bundles loaded privately in sequence: <strong>767d45f6ce40 → e0d053bc6732 → 767d45f6ce40</strong>. Each process exited normally and was reaped before the next copy. Both recording/source API replies preserved exact counters and complete descriptors, including new fields unknown to the older build.</p><p><strong>All 22 copied original session files and two action receipts stayed unchanged.</strong> Original production state hashes also stayed exact. An authored saved mid-recording checkpoint became interrupted with non-final counters and incomplete source metadata; fallback and forward recovery retained that uncertainty. Existing byte-identical decoded media evidence was reused.</p><p class="note">This is a private signed bundle/state drill for one terminal session, not production launchd rollback or crashed live-producer recovery. No capture, input listener, grant request, model turn or UI replay occurred. Production remains PID15145/build767d45f6ce40. Input Monitoring is still awaiting human authentication; remaining app, consumer, insurance and resource gates continue.</p><details><summary>Read twenty-first-pass evidence and restoration limits</summary><pre>' + html.escape(notes21) + '</pre></details></section>'
    page = page.replace('<section id="twentieth-pass">', section21 + '<section id="twentieth-pass">')
if (args.evidence / 'gates-v22/qualification-summary.json').exists():
    summary22 = json.loads((args.evidence / 'gates-v22/qualification-summary.json').read_text())
    notes22 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-second pass:', 1)[1].split('## Twenty-first pass:', 1)[0]
    page = page.replace('<a href="#twenty-first-pass">Latest qualification</a>', '<a href="#twenty-second-pass">Latest qualification</a>')
    page = page.replace('Twenty-one staged qualification passes', 'Twenty-two staged qualification passes')
    section22 = '<section id="twenty-second-pass"><h2>Shared app baselines now have a targeted planning tool</h2><p><strong>computer_use_plan</strong> and the native evidence CLI consume the existing shared app store. Exact environment keys identify missing baselines, expiry, conflicts, mixed and unknown outcomes. A reported pass becomes a reuse candidate only with caller-confirmed environment and complete observation-window coverage. An older failure beyond the 100-observation window prevents newest-pass certainty.</p><p><strong>All 13 targeted tests passed.</strong> Fresh MCP discovery/readback ran with model and transport paths forbidden inside servers. Planning validates bounded regular evidence files and refuses oversized buckets, files and symlinks. It references saved evidence without fetching or grading its contents.</p><p>Actual CLI kept the prior Chrome readiness result unknown. Three native fixture observations stayed distinct: pixel pass, readiness mixed, input telemetry unknown. Keyboard shortcuts remain missing. Unknown fixture/provider/profile dimensions keep every reuse candidate false. Both recorder replies survived central import exactly: expired/interrupted and closed/delivered.</p><p class="note">This is explicit shared learning and targeted planning, not automatic UI ingestion, historical success grading or model training. Existing clients discover the new tool at their safe next launch; no peer restart occurred. Input Monitoring still awaits human authentication. Daily-app baseline execution, typed verification/cleanup and broader insurance/resource gates remain open.</p><details><summary>Read twenty-second-pass evidence and shared learning limits</summary><pre>' + html.escape(notes22) + '</pre></details></section>'
    page = page.replace('<section id="twenty-first-pass">', section22 + '<section id="twenty-first-pass">')
if (args.evidence / 'gates-v23/qualification-summary.json').exists():
    summary23 = json.loads((args.evidence / 'gates-v23/qualification-summary.json').read_text())
    notes23 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-third pass:', 1)[1].split('## Twenty-second pass:', 1)[0]
    page = page.replace('<a href="#twenty-second-pass">Latest qualification</a>', '<a href="#twenty-third-pass">Latest qualification</a>')
    page = page.replace('Twenty-two staged qualification passes', 'Twenty-three staged qualification passes')
    section23 = '<section id="twenty-third-pass"><h2>Workflow audits now separate verification and cleanup</h2><p>New typed outcomes link to an immutable receipt in the exact session. Dispatch/delivery, verification and cleanup remain separate. A delivered or even verified receipt leaves the other dimensions unknown without an explicit outcome. Conflicting history, future observations, truncation and unknown restart ends remain visible; audit counts are reported persisted scopes, not task success rates.</p><p><strong>All 28 targeted tests passed.</strong> The supported workflow wrapper runs an operation once, closes its service scope before long verification, attempts supplied cleanup once and never replays UI after receipt or publication failure. Missing/invalid proof stays unknown. Fresh guarded MCP advertises seven evidence tools.</p><p>An actual installed source consumer reused <strong>byte-identical 307-sample media/source proof</strong>, verified readback and confirmed its own action cleanup. No new capture, render, UI, permission request or restart occurred. The typed CLI audit covers three owned episodes: two verified checks and one failed readiness check; one completed cleanup and two partial cleanups.</p><p class="note">The earlier fixture/session remain retained for the approved input-grant canary, so their cleanup is honestly partial. Historical 2655-call quality, routine skill/provider adoption, daily-app capture, physical input and measured insurance/resources remain open. Evidence contents and actor/result claims are not authenticated by the store. Native CUA still requires explicit bracketing.</p><details><summary>Read twenty-third-pass evidence and workflow audit limits</summary><pre>' + html.escape(notes23) + '</pre></details></section>'
    page = page.replace('<section id="twenty-second-pass">', section23 + '<section id="twenty-second-pass">')
if (args.evidence / 'gates-v24/qualification-summary.json').exists():
    summary24 = json.loads((args.evidence / 'gates-v24/qualification-summary.json').read_text())
    notes24 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-fourth pass:', 1)[1].split('## Twenty-third pass:', 1)[0]
    page = page.replace('<a href="#twenty-third-pass">Latest qualification</a>', '<a href="#twenty-fourth-pass">Latest qualification</a>')
    section24 = '<section id="twenty-fourth-pass"><h2>Chrome native select needs a separate display layer</h2><p><strong>The actual twelve-row select survived in encoded display footage while child-enabled window and application-filtered sources omitted it.</strong> Four small takes supplied ' + str(summary24['exact_muxed_samples']) + ' exact muxed/source timestamps. The first two lost their popup and remain inconclusive; their movement, missing geometry and off-screen evidence are preserved.</p>'
    section24 += figure('gates-v24/display-popup-only.png', 'Actual encoded display crop of the authored Chrome select. Only the popup is shown; unrelated background remains private.')
    section24 += '<p>The owned native New Window action repaired initial off-Space readiness. Moving only that window to the external display recovered it after interference. The supplied popup crop achieved glyph overlap of 0.983 after a measured one-pixel horizontal offset from the earlier reference. The failed zero-offset check remains; arbitrary popup tracking is unqualified.</p><p>Four scoped app observations were appended and read back in shared computer-use facts. Unknown provider/profile versions keep planner reuse false. Native cleanup was explicitly bracketed and independently verified after its UI read timed out, without replay. Owned tabs/window/server/session are settled.</p><p class="note">This is Chrome 154.0.8037.98 / macOS 25F80 on one external display. A covered base remained absent from the display source, so full-shot recovery and motion insurance stay open. Earlier UI actions lacked receipts. Input Monitoring still awaits human Touch ID; warning host pressure kept paired motion pending. Installed production remains 767d45f6ce40.</p><details><summary>Read twenty-fourth-pass evidence and remaining boundaries</summary><pre>' + html.escape(notes24) + '</pre></details></section>'
    page = page.replace('<section id="twenty-third-pass">', section24 + '<section id="twenty-third-pass">')
if (args.evidence / 'gates-v25/qualification-summary.json').exists():
    notes25 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-fifth pass:', 1)[1].split('## Twenty-fourth pass:', 1)[0]
    page = page.replace('<a href="#twenty-fourth-pass">Latest qualification</a>', '<a href="#twenty-fifth-pass">Latest qualification</a>')
    page = page.replace('Twenty-three staged qualification passes', 'Twenty-five staged qualification passes')
    section25 = '<section id="twenty-fifth-pass"><h2>Native skill workflows now have a practical evidence path</h2><p>The current native computer-use skill links shared app facts, explicit action bracketing and separate verification/cleanup. The public CLI imports terminal recorder replies with exact clock strings and unknown restart ends; regular UTF-8 input files are bounded to 64,000 bytes.</p><p><strong>Twelve targeted checks and one fresh native click canary passed.</strong> The fixture received one down/up pair inside exact service bounds, and fresh AX counters increased once. The terminal reply and verified/partial-cleanup outcome independently read back. A previous reply imported twice with identical identity and no duplicate coverage.</p><p class="note">This is explicit skill adoption, not automatic CUA interception or a historical task success audit. The standard skill validator lacked PyYAML; a declared YAML/structural fallback passed. Fixture/session cleanup remained partial for the input canary. Actor identity remains unknown.</p><details><summary>Read twenty-fifth-pass evidence and adoption limits</summary><pre>' + html.escape(notes25) + '</pre></details></section>'
    page = page.replace('<section id="twenty-fourth-pass">', section25 + '<section id="twenty-fourth-pass">')
if (args.evidence / 'gates-v26/qualification-summary.json').exists():
    notes26 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-sixth pass:', 1)[1].split('## Twenty-fifth pass:', 1)[0]
    page = page.replace('<a href="#twenty-fifth-pass">Latest qualification</a>', '<a href="#twenty-sixth-pass">Latest qualification</a>')
    page = page.replace('Twenty-five staged qualification passes', 'Twenty-six staged qualification passes')
    section26 = '<section id="twenty-sixth-pass"><h2>Installed input access now has delivered-event proof</h2><p><strong>Input Monitoring is enabled for the signed installed recorder.</strong> Taylor completed macOS authentication. One idle fenced restart verified PID 80100 with unchanged build 767d45f6ce40; a fresh subscription reported listening access.</p><p>The native canary retained <strong>17 input rows and 262 exact muxed/source timestamps</strong>. All six app-delivered gesture transitions matched retained timestamps, types, destination and positions inside the declared action. Four Command+Shift+K shortcut transitions were addressed to the fixture despite another app being globally foreground. No input gaps, queue overflow or journal loss were observed.</p><p class="note">The shortcut destination is observed; semantic execution, physical/global shortcuts, other providers and actor identity remain unqualified. Provider callback density differs from app delivery density. The take/action settled and listener returned idle; fixture/session remain for deeper checks. The specific installed-input checklist gate is completed, while broader relevance and production gates remain open.</p><details><summary>Read twenty-sixth-pass grant, event and cleanup evidence</summary><pre>' + html.escape(notes26) + '</pre></details></section>'
    page = page.replace('<section id="twenty-fifth-pass">', section26 + '<section id="twenty-fifth-pass">')
if (args.evidence / 'gates-v27/qualification-summary.json').exists():
    notes27 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-seventh pass:', 1)[1].split('## Twenty-sixth pass:', 1)[0]
    page = page.replace('<a href="#twenty-sixth-pass">Latest qualification</a>', '<a href="#twenty-seventh-pass">Latest qualification</a>')
    page = page.replace('Twenty-six staged qualification passes', 'Twenty-seven staged qualification passes')
    section27 = '<section id="twenty-seventh-pass"><h2>Real shortcuts exposed and repaired a keyboard-scope leak</h2><p><strong>A native two-window oracle executed real shortcuts without a text field.</strong> Twelve delivered key transitions matched source exactly. Six belonged to the other same-app window: they remained explicitly unresolved and inherited no wrong action token.</p><p>A different-app test found two unmodified keys retained through foreground fallback despite an explicit other-app destination. That failed take remains. The repair uses foreground only when destination is unknown; target-app keys and bounded shortcut/all candidates remain available.</p><p><strong>The signed installed repair passed a fresh delivery canary.</strong> Build 53b202f58af8 excluded both unrelated unmodified transitions and retained all four shortcut/modifier candidates. The other app executed its shortcut once. Twelve focused and 141 mechanical/input/action checks passed; three takes supplied 373 exact muxed/source timestamps. Input Monitoring survived the fenced update.</p><p class="note">Same-app window ambiguity, physical/global completeness, density and actor identity remain open. The bounded human physical request ended without delivery or reply, so it stays pending. All owned fixtures and both sessions are settled; recorder input is idle. Shared facts preserve the earlier failure and the new versioned pass. This improves one tested boundary without resetting the broader qualification work.</p><details><summary>Read twenty-seventh-pass keyboard, failure and recovery evidence</summary><pre>' + html.escape(notes27) + '</pre></details></section>'
    page = page.replace('<section id="twenty-sixth-pass">', section27 + '<section id="twenty-sixth-pass">')
if (args.evidence / 'gates-v28/qualification-summary.json').exists():
    notes28 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-eighth pass:', 1)[1].split('## Twenty-seventh pass:', 1)[0]
    page = page.replace('<a href="#twenty-seventh-pass">Latest qualification</a>', '<a href="#twenty-eighth-pass">Latest qualification</a>')
    page = page.replace('Twenty-seven staged qualification passes', 'Twenty-eight staged qualification passes')
    section28 = '<section id="twenty-eighth-pass"><h2>Retina popup capture preserves fitted geometry</h2><p><strong>Chrome’s select behaved differently on the built-in 2x display.</strong> A preexisting overflow popup appeared in both the child-enabled window take and a bounded display crop. The earlier external-display omission remains a separate qualified case.</p><table><tr><th>Source</th><th>Observed result</th><th>Limit</th></tr><tr><td>Retina display crop</td><td>All twelve rows at 2x; 98.9% supplied glyph overlap.</td><td>Display pixels can include unrelated content or lose the base to occlusion.</td></tr><tr><td>Child-enabled window</td><td>Content fitted to 1.372678 pixels per desktop point. Saved map aligned base marker edges exactly and popup glyphs at 90.2% overlap.</td><td>Preexisting static overflow; do not assume backing scale equals content scale.</td></tr><tr><td>Contained popup opened during paired takes</td><td>Visible with child inclusion enabled; absent with it disabled. Both maps stayed at 2x.</td><td>The popup opened at a different position inside the base. Dynamic overflow shrink/restore remains open.</td></tr></table><p>Four takes supplied <strong>630 exact muxed/source samples</strong>. A bounded metadata probe observed a new same-PID layer-101 candidate absent, present, present and absent around the authored popup. PID, layer and overlap remain candidate clues for general parent ownership.</p><div class="pair">' + figure('gates-v28/retina-select-proof.menu.png', 'Display source: the authored overflow select at 2x.') + figure('gates-v28/window-repeatable-proof.menu.png', 'Window source: the same overflow select after fitted scaling.') + '</div><p class="note">New kits verify supplied source crops and bounded candidate geometry; visual composition remains deferred. Three exact-environment facts were read back centrally, with unknown provider/profile blocking unconfirmed reuse. All owned window, server and session resources are settled; recorder remains installed and idle. Broader popup tracking, dynamic fitting, motion insurance and physical-input coverage remain open.</p><details><summary>Read Retina popup, geometry and child-option evidence</summary><pre>' + html.escape(notes28) + '</pre></details></section>'
    page = page.replace('<section id="twenty-seventh-pass">', section28 + '<section id="twenty-seventh-pass">')
if (args.evidence / 'gates-v29/qualification-summary.json').exists():
    notes29 = Path(__file__).with_name('GATES.md').read_text().split('## Twenty-ninth pass:', 1)[1].split('## Twenty-eighth pass:', 1)[0]
    page = page.replace('<a href="#twenty-eighth-pass">Latest qualification</a>', '<a href="#twenty-ninth-pass">Latest qualification</a>')
    page = page.replace('Twenty-eight staged qualification passes', 'Twenty-nine staged qualification passes')
    section29 = '<section id="twenty-ninth-pass"><h2>A moving backup preserved the shot after the display writer failed</h2><p><strong>The isolated window source kept the full 50-second changing scene through a real 20-second opaque obstruction.</strong> All 1,463 backup samples matched source timestamps. Before failure, the paired counters agreed within two nominal 60 Hz ticks; both declared source maps matched.</p><div class="pair">' + figure('gates-v29/published-obstruction.jpg', 'Actual display verification during the take: the owned opaque cover obstructs the source.') + figure('gates-v29/motion-insurance-proof-recovered-backup.png', 'Actual encoded window backup during the obstruction: motion and counter remain visible.') + '</div><p>The display writer accepted 77 submissions but persisted only 75 samples. The backup remained continuously readable and changing, with 575 distinct counter values under the cover. A saved recovery map selects actual backup samples for the missing primary interval. Earlier pairs lacked actual obstruction and remain failed test preconditions.</p><p><strong>An isolated writer probe reproduced sparse timing failure without screen capture.</strong> At the nanosecond media timescale, 1.9 and 2.1-second sample gaps passed; 2.2 seconds and longer failed with underlying OSStatus −17771. Microsecond timing and one-second held-buffer controls completed. This points to a narrow timing boundary; production has not been repaired yet.</p><p class="note">Full-shot backup coverage is verified for this authored point-resolution fixture. Reliable paired writing, sustained encoder/GPU cost, broader app/menu recovery and production-duration estimates remain open. Pressure stayed at warning level; the failed primary prevents a successful paired cost claim. Next: bounded explicit held frames that preserve exact source timing, then actual sparse-resume qualification. All owned fixtures and session resources are settled; the installed recorder and Input Monitoring remain active.</p><details><summary>Read motion recovery, failed writer and isolated timing evidence</summary><pre>' + html.escape(notes29) + '</pre></details></section>'
    page = page.replace('<section id="twenty-eighth-pass">', section29 + '<section id="twenty-eighth-pass">')
if (args.evidence / 'gates-v30/qualification-summary.json').exists():
    notes30 = Path(__file__).with_name('GATES.md').read_text().split('## Thirtieth pass:', 1)[1].split('## Twenty-ninth pass:', 1)[0]
    page = page.replace('<a href="#twenty-ninth-pass">Latest qualification</a>', '<a href="#thirtieth-pass">Latest qualification</a>')
    page = page.replace('Twenty-nine staged qualification passes', 'Thirty staged qualification passes')
    section30 = '<section id="thirtieth-pass"><h2>Sparse writer repair is delivered; moving insurance now passes</h2><p><strong>Signed build f314bb340344 is installed.</strong> Exact nanosecond timing remains intact. Static intervals use explicitly held copies of the last encoded source, and resumed pixels never appear earlier. Oversized gaps or unfillable backpressure stop only the affected take.</p><p>The actual 50-second display/window pair survived a 20-second obstruction: <strong>2,371 exact muxed/source samples, zero dropped frames and zero journal loss</strong>. The display kept 26 labeled sparse held frames; the backup kept 575 changing counter values under the cover. Its dense recovery map selects 586 source samples through the obstruction.</p><div class="pair">' + figure('gates-v30/live-insurance-proof-covered-primary.png', 'Actual encoded display source during obstruction: a held opaque cover, with declared source provenance.') + figure('gates-v30/live-insurance-proof-recovered-backup.png', 'Actual encoded window backup during the same interval: continuously changing scene.') + '</div><p>Fifteen controlled recording checks and prior-source pixel QA passed. The raw unpadded control preserves the real writer error chain; the repaired path retains exact samples. The earlier finalization and peer-isolation checks also passed. Failed harness clock ordering and the zero-duration tail remain documented.</p><table><tr><th>Delivered check</th><th>Observed result</th><th>Limit</th></tr><tr><td>Production release</td><td>One idle fenced build; exact signed cache reused, prior bundle saved, seven earlier state/media files unchanged.</td><td>No live rollback or forced peer adapter restart.</td></tr><tr><td>Installed smoke</td><td>48 exact samples and actual loaded MCP source readback. Fresh Input Monitoring access active.</td><td>Protected-input gap remained visible; no complete keyboard claim.</td></tr><tr><td>Successful paired cost</td><td>50 resource observations; aggregate recorder 0.063 CPU cores and 51.7 MiB peak RSS; two 8.3 MB files.</td><td>Warning pressure and other host work; no isolated GPU, capacity or P80 claim.</td></tr></table><p class="note">The checklist now has 35 completed checks, 20 partial and 1 deferred. Broader app/menu fallback, dynamic popup fitting, physical/provider coverage and final production-mode expectations remain open. All owned fixtures, sessions and isolated engine are settled; installed recorder is idle. Visual composition remains deferred.</p><details><summary>Read sparse repair, paired footage, delivery and remaining limits</summary><pre>' + html.escape(notes30) + '</pre></details></section>'
    page = page.replace('<section id="twenty-ninth-pass">', section30 + '<section id="twenty-ninth-pass">')
if (args.evidence / 'gates-v31/qualification-summary.json').exists():
    notes31 = Path(__file__).with_name('GATES.md').read_text().split('## Thirty-first pass:', 1)[1].split('## Thirtieth pass:', 1)[0]
    page = page.replace('<a href="#thirtieth-pass">Latest qualification</a>', '<a href="#thirty-first-pass">Latest qualification</a>')
    page = page.replace('Thirty staged qualification passes', 'Thirty-one staged qualification passes')
    section31 = '<section id="thirty-first-pass"><h2>Agents can assess production expectations before a take</h2><p><strong>Read-only production planning is delivered through CLI and fresh MCP adapter 0.9.0.</strong> It reports background/cooperative/reserved expectations, caller-declared interval coverage, cursor-layer limits, observed obstacles and recovery choices. It starts no capture, drives no UI and keeps user input available.</p><p>Five new policy/MCP tests and three adjacent option/reconnect tests passed. A live owned adapter and CLI readback preserved the installed recorder PID and idle state. Planning distinguished off-Space UI from passive capture and missing alignment from an approved interval. A candidate still requires actual source and provider checks.</p><table><tr><th>Planning result</th><th>What it means</th></tr><tr><td>Needs resolution</td><td>Resolve a named runtime or alignment obstacle before the intended production work.</td></tr><tr><td>Candidate requires source check</td><td>No observed planning obstacle; native delivery and usable encoded pixels remain unverified.</td></tr><tr><td>Measured costs</td><td>The authored 50-second pair is a scoped benchmark. Requested app, GPU/thermals, longer duration and P80 remain unqualified.</td></tr></table><p><strong>Chrome dynamic fitting remains partial.</strong> The owned tab opened, but full application reads timed out and a shortcut did not establish a new native window. Recorder inventory kept the target off Space. No capture or shortcut replay followed; existing pixel passes remain valid for their recorded scope.</p><p>Three terminal scopes have separate outcomes: two verified, one failed, all cleanup completed. The owned tab/server/session and fresh MCP are closed; seven existing tabs were preserved. A mixed shared readiness fact keeps unknown environment dimensions explicit.</p><p class="note">The checklist now has 37 completed checks, 18 partial and 1 deferred. Human production expectations and the published clean-layer contract are completed for their written scopes. Broader app/menu/provider/capacity work continues. Existing harness adapter policy remains unknown; no peer restart or native rebuild was used.</p><details><summary>Read production planning, failed readiness and scoped completion</summary><pre>' + html.escape(notes31) + '</pre></details></section>'
    page = page.replace('<section id="thirtieth-pass">', section31 + '<section id="thirtieth-pass">')
page += figure('software-cursor-rect.png', 'Capture-level hiding: helper pointer remains below the text field.')
page += figure('software-cursor-rect-excluding-pid.png', 'Helper app excluded: pointer is gone; app-painted arrow remains.')
page += '</div><details><summary>Inspect the surviving caret and browser automation pointer in actual video</summary><div class="pair">'
page += figure('native-video-caret.jpg', 'Native video: blue text caret and magenta app-painted arrow survive pointer hiding.')
page += figure('chrome-video-pointer.jpg', 'Chrome video: pointer-like residual beside Open HTML menu survives pointer hiding.')
page += '</div></details><div>'
page += '''</div><p>Native recorded footage also retained a blinking text caret. Chrome isolated video retained a pointer-like automation residual near the HTML-menu button; its cause is still open. Capture configuration cannot be treated as a universal clean-footage guarantee.</p><h2>Child surfaces change the menu result</h2><p>The same native menu disappeared when child inclusion was disabled and appeared when enabled. Its nested submenu was captured too. This is one app/OS combination, not a cross-app guarantee.</p><div class="switch"><button data-image="without" aria-pressed="true">Child inclusion disabled</button><button data-image="with" aria-pressed="false">Child inclusion enabled</button></div>'''
page += f'<figure><img id="menu-image" src="{image("edge-menu-included-window-false.png")}" alt="Native menu omitted with child inclusion disabled"><figcaption id="menu-caption">Menu omitted from the display-bound window capture.</figcaption></figure>'
page += '''<h2>Input delivery beats global focus</h2><p>The destination-aware retest retained <strong>46 key/modifier events</strong> addressed to the fixture. The fixture was foreground for <strong>none of them</strong>. Another 646 events contributed counts only. A focus-only rule would discard legitimate agent input; those outside-scope counts are not a contamination rate.</p><p>All retained events named the current computer-use helper as source, but its zero-valued tags did not identify a durable agent session. Action receipts and uncertainty are still necessary. AX actions can change windows without a pointer event.</p>
<h2>Time and redundancy have useful foundations</h2><table><tr><th>Probe</th><th>Observed result</th><th>What remains</th></tr><tr><td>Frame clock and geometry</td><td>1,178 complete frames. Converted display time and PTS agreed within 1 ns. Screen rect followed an 80-point move.</td><td>Actual action-to-pixel bound; resizing, sleep/wake and display changes.</td></tr><tr><td>Capture callback</td><td>Median lag 0.391 ms; maximum 10.953 ms in this probe.</td><td>Realistic high-motion/load qualification.</td></tr><tr><td>Matched source lanes</td><td>Two 35-second, 1400×964 recordings; zero dropped frames. Isolated footage survived the display crop’s occlusion/move.</td><td>CPU, memory, encoder, thermal and storage budget. About 2.62 MB here is a small static-fixture result.</td></tr><tr><td>Shared computer use</td><td>Native control/typing/selection/menu/cleanup checks and bridge MCP discovery passed. History inventory found 2,555 calls in 32 chats since September 17.</td><td>Historical success audit and a fresh delegated bridge run. Counts/discovery prove neither.</td></tr></table></section>
<section id="strategy"><h2>The proposed service contract</h2><table><tr><th>Owner</th><th>Responsibilities</th></tr><tr><td>Shared computer-use capabilities</td><td>App/provider/version facts; action receipts; delivery evidence; broad canaries plus stable per-app depth lanes; human production expectations.</td></tr><tr><td>Recorder</td><td>Normalized host timeline and geometry segments; explicit child/overlay capture options; source coverage and disturbances; measured recovery/insurance lanes.</td></tr><tr><td>Agent/director</td><td>Intent and rich contextual blocks; semantic relevance refinements with reasons; choice of cost/fidelity and recovery plan.</td></tr><tr><td>Later composition phase</td><td>Cursor/effect recipes, transient reintegration, brief visual/audio cues and final rendering. Deferred here.</td></tr></table><p>Consumers should receive synchronized sources, event/action journals, transforms, context blocks and QA. They should not implement clock calibration or coordinate reconstruction. Verification levels progress from metadata, to sparse source frames, to short previews, to full rendering later.</p><p>Production modes should say whether work is background-cooperative, display-reserved or awaiting an approved interval. Detect interruptions and save the shot; do not block the user prophylactically. P80 estimates need actual measurements. A second display does not isolate every OS shortcut or focus effect.</p></section>
<section id="limits"><h2>The next qualification gates</h2><p>Current item states, scoped evidence and next acceptance steps are maintained in the <a href="checklist.html">qualification checklist</a>. Earlier sections retain historical results and failures.</p><ol><li>Extend pointer mapping to remaining providers and drag/scroll, improve contextual input/receipt coverage and qualify physical sleep/wake. Preserve the completed color, clock and controlled tap evidence.</li><li>Finish Chrome native-select and deeper overflow checks. A supplied native popup crop has spatial/encoded-source proof; simultaneous shot recovery stays open. Preview exclusion lifetime passed its candidate scope; preserve that evidence.</li><li>Preserve the completed sparse-writer repair and bounded moving-backup proof. Extend recovery to app/menu surfaces, set realistic resource/admission expectations and complete the shared workflow outcome audit.</li><li>Installed passive consumers passed. Verify loaded MCP replay policy at safe consumer launches, preserve the passed private restoration drill while qualifying broader recovery boundaries, then reconcile final agent runbooks. Visual composition remains next phase.</li></ol><p class="note">The disposable fixture crashed while closing a retained AppKit window. Its lifetime handling was repaired, and closing the occlusion and main windows was verified. One telemetry run spanning the relaunch was discarded. The recorder remained available.</p><p>Chrome native input could not reach its off-Space window even though browser-tab automation worked. Several capture modes also returned SCK -3811 errors. Later visible Chrome native-menu takes passed in their tested scope; select, nested overflow and cross-mode reliability still need qualification.</p></section>
<details><summary>Read the full implementation strategy and acceptance gates</summary><pre>'''
page += html.escape(strategy)
page += '</pre></details><details><summary>Evidence and repeatable kit</summary><p>Private artifacts: <code>' + html.escape(str(args.evidence)) + '</code></p><p>Source kit: <code>/Users/taylor/src/github/dotfiles/src/record-screen/qualification/</code></p><p>Recorder session: ses_znmm2ude. Recordings: rec_9ysm6u63, rec_329z2bru, rec_pwxrgkwx, rec_cu7uaw6w. Owned fixture, tab, servers and taps were closed/stopped; no active recordings remained.</p></details></main><script>'
page += 'const images=' + __import__('json').dumps({'without': image('edge-menu-included-window-false.png'), 'with': image('edge-menu-included-window-true.png')}) + ';'
page += '''for(const b of document.querySelectorAll('[data-image]'))b.addEventListener('click',()=>{for(const other of document.querySelectorAll('[data-image]'))other.setAttribute('aria-pressed',String(other===b));const shown=b.dataset.image==='with';document.querySelector('#menu-image').src=images[b.dataset.image];document.querySelector('#menu-image').alt=shown?'Native menu present with child inclusion enabled':'Native menu omitted with child inclusion disabled';document.querySelector('#menu-caption').textContent=shown?'Native menu included in the same display-bound window capture.':'Menu omitted from the display-bound window capture.'});</script></html>'''
workflow = checklist_data['workflow']
page = page.replace('<main><nav>', '<main><p class="note"><strong>Qualification ' + html.escape(workflow['state']) + '.</strong> ' + html.escape(workflow['note']) + ' Current acceptance states are in the checklist; earlier sections retain historical results.</p><nav>', 1)
page = page.replace('</style>', '.checklist-link{margin-left:auto;font-weight:600}.checklist-link:focus-visible{outline:3px solid var(--blue);outline-offset:4px}</style>', 1)
page = page.replace('</nav>', '<a class="checklist-link" href="checklist.html">Go to checklist</a></nav>', 1)
render_checklist(checklist_data, args.output.with_name('checklist.html'), args.output.name)
args.output.write_text(page)
print(f'Report saved: {args.output} ({args.output.stat().st_size} bytes)')
